import { BAI, BamFile } from '../src'

import { LocalFile } from 'generic-filehandle'
import FakeRecord from './fakerecord'

class HalfAbortController {
  constructor() {
    this.signal = { aborted: false }
  }

  abort() {
    this.signal.aborted = true
  }
}

describe('index formats', () => {
  it('loads volvox-sorted.bam.bai', async () => {
    const ti = new BAI({
      filehandle: new LocalFile(require.resolve('./data/volvox-sorted.bam.bai')),
    })
    const indexData = await ti.parse()
    expect(indexData.bai).toEqual(true)
    expect(await ti.lineCount(0)).toEqual(9596)
    expect(await ti.hasRefSeq(0)).toEqual(true)
  })
  it('loads volvox-sorted.bam in similar test', async () => {
    const ti = new BamFile({
      bamPath: require.resolve('./data/volvox-sorted.bam'),
    })
    await ti.getHeader()
    expect(await ti.lineCount('ctgA')).toEqual(9596)
    expect(await ti.hasRefSeq('ctgA')).toEqual(true)
  })
})

describe('index human data', () => {
  it('loads 1000 genomes bai', async () => {
    const ti = new BAI({
      filehandle: new LocalFile(
        require.resolve('./data/HG00096.chrom20.ILLUMINA.bwa.GBR.low_coverage.20120522.bam.bai'),
      ),
    })
    const indexData = await ti.parse()
    expect(indexData.bai).toEqual(true)
    expect(await ti.hasRefSeq(19)).toEqual(true)
    expect(await ti.lineCount(19)).toEqual(2924253)
  })
  it('can abort loading 1000 genomes bai', async () => {
    const ti = new BAI({
      filehandle: new LocalFile(
        require.resolve('./data/HG00096.chrom20.ILLUMINA.bwa.GBR.low_coverage.20120522.bam.bai'),
      ),
    })
    const aborter = new HalfAbortController()
    const indexDataP = ti.parse(aborter.signal)
    aborter.abort()
    await expect(indexDataP).rejects.toThrow(/aborted/)
  })
})
describe('bam header', () => {
  it('loads volvox-sorted.bam', async () => {
    const ti = new BamFile({
      bamPath: require.resolve('./data/volvox-sorted.bam'),
    })
    await ti.getHeader()
    expect(ti.header).toEqual('@SQ	SN:ctgA	LN:50001\n')
    expect(ti.chrToIndex.ctgA).toEqual(0)
    expect(ti.indexToChr[0]).toEqual({ refName: 'ctgA', length: 50001 })
    const ret = await ti.indexCov('ctgA')
    expect(ret).toMatchSnapshot()
  })
  it('loads volvox-sorted.bam with csi index', async () => {
    const ti = new BamFile({
      bamPath: require.resolve('./data/volvox-sorted.bam'),
      csiPath: require.resolve('./data/volvox-sorted.bam.csi'),
    })
    await ti.getHeader()
    expect(ti.header).toEqual('@SQ	SN:ctgA	LN:50001\n')
    expect(ti.chrToIndex.ctgA).toEqual(0)
    expect(ti.indexToChr[0]).toEqual({ refName: 'ctgA', length: 50001 })
  })
})

describe('bam records', () => {
  let ti
  beforeEach(() => {
    ti = new BamFile({
      bamPath: require.resolve('./data/volvox-sorted.bam'),
    })
    return ti.getHeader()
  })
  it('gets features from volvox-sorted.bam', async () => {
    const records = await ti.getRecordsForRange('ctgA', 0, 1000)
    expect(records.length).toEqual(131)
    expect(records[0].get('start')).toEqual(2)
    expect(records[0].get('end')).toEqual(102)
    expect(records[0].get('cigar')).toEqual('100M')
    expect(records[0].get('name')).toEqual('ctgA_3_555_0:0:0_2:0:0_102d')
    expect(records[0].get('qual')).toEqual(
      '17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17',
    )
    expect(records[0].get('md')).toEqual('100')
    expect(records[0].getReadBases()).toEqual(
      'TTGTTGCGGAGTTGAACAACGGCATTAGGAACACTTCCGTCTCTCACTTTTATACGATTATGATTGGTTCTTTAGCCTTGGTTTAGATTGGTAGTAGTAG',
    )
  })
  it('gets features from the end of volvox-sorted.bam', async () => {
    const records = await ti.getRecordsForRange('ctgA', 47457, 50001)
    expect(records.length).toEqual(473)
  })
  it('gets out of bounds from volvox-sorted.bam', async () => {
    const records = await ti.getRecordsForRange('ctgA', 60000, 70000)
    expect(records.length).toEqual(0)
  })
  it('gets large chunk from volvox-sorted.bam', async () => {
    const promises = []
    const win = 1000
    for (let i = 0; i < 50000; i += win) {
      const records = ti.getRecordsForRange('ctgA', i, i + win)
      promises.push(records)
    }
    const recs = await Promise.all(promises)
    expect(recs.every(record => record.length > 0)).toBeTruthy()
  })

  it('gets specific weird chunk of volvox-sorted.bam', async () => {
    const records = await ti.getRecordsForRange('ctgA', 32749, 32799)
    expect(records.length).toEqual(13)
  })
  it('gets specific other weird chunk of volvox-sorted.bam', async () => {
    const records = await ti.getRecordsForRange('ctgA', 32799, 32849)
    expect(records.length).toEqual(11)
  })
})

describe('bam deep record check', () => {
  it('deep check volvox-sorted.bam', async () => {
    const ti = new BamFile({
      bamPath: require.resolve('./data/volvox-sorted.bam'),
    })
    await ti.getHeader()
    const records = await ti.getRecordsForRange('ctgA', 0, 10)
    expect(records).toMatchSnapshot()
  })
})

describe('1000 genomes bam check', () => {
  it('deep check 1000 genomes', async () => {
    const ti = new BamFile({
      bamPath: require.resolve('./data/1000genomes_hg00096_chr1.bam'),
      csiPath: require.resolve('./data/1000genomes_hg00096_chr1.bam.csi'),
    })
    await ti.getHeader()
    const records = await ti.getRecordsForRange('1', 0, 1000)
    expect(records).toMatchSnapshot()
  })
  it('deep check 1000 genomes bai', async () => {
    const ti = new BamFile({
      bamPath: require.resolve('./data/1000genomes_hg00096_chr1.bam'),
    })
    await ti.getHeader()
    const records = await ti.getRecordsForRange('1', 0, 1000)
    expect(records).toMatchSnapshot()
  })
  it('start to deep check 1000 genomes but abort instead', async () => {
    const aborter = new HalfAbortController()
    const ti = new BamFile({
      bamPath: require.resolve('./data/1000genomes_hg00096_chr1.bam'),
      csiPath: require.resolve('./data/1000genomes_hg00096_chr1.bam.csi'),
    })
    const recordsP = ti
      .getHeader(aborter.signal)
      .then(() => ti.getRecordsForRange('1', 0, 1000, { signal: aborter.signal }))
    aborter.abort()
    await expect(recordsP).rejects.toThrow(/aborted/)
  })
})

describe('ecoli bam check', () => {
  it('check ecoli header and records', async () => {
    const ti = new BamFile({
      bamPath: require.resolve('./data/ecoli_nanopore.bam'),
    })
    const header = await ti.getHeader()
    const records = await ti.getRecordsForRange('ref000001|chr', 0, 100)
    expect(header).toMatchSnapshot()
    expect(records).toMatchSnapshot()
  })
})
describe('BamFile with test_deletion_2_0.snps.bwa_align.sorted.grouped.bam', () => {
  let b
  beforeEach(async () => {
    b = new BamFile({
      bamPath: 'test/data/test_deletion_2_0.snps.bwa_align.sorted.grouped.bam',
    })
    await b.getHeader()
  })

  it('constructs', () => {
    expect(b).toBeTruthy()
  })

  it('loads some data', async () => {
    const features = await b.getRecordsForRange('Chromosome', 17000, 18000)
    expect(features.length).toEqual(124)
    expect(features.every(feature => feature.get('seq_length') === feature.getReadBases().length)).toBeTruthy()
  })
})

describe('BamFile tiny', () => {
  it('loads some data', async () => {
    const b = new BamFile({
      bamPath: 'test/data/tiny.bam',
    })
    await b.getHeader()
    const features = await b.getRecordsForRange('22', 30000000, 30010000)
    expect(features.length).toEqual(2)
  })
})

describe('BamFile secondary', () => {
  it('checks secondary', async () => {
    const b = new BamFile({
      bamPath: 'test/data/secondary.bam',
    })
    await b.getHeader()
    const features = await b.getRecordsForRange('20', 10761157, 10761387)
    const dups = features.map(f => f.isDuplicate()).reduce((x, y) => x + y)
    expect(dups).toEqual(2)
  })
})
describe('BamFile empty', () => {
  it('loads but does not crash', async () => {
    const b = new BamFile({
      bamPath: 'test/data/empty.bam',
    })
    await b.getHeader()
    const features = await b.getRecordsForRange('22', 30000000, 30010000)
    expect(features.length).toEqual(0)
  })
})

describe('BamFile with B tags', () => {
  it('test B tags', async () => {
    const b = new BamFile({
      bamPath: 'test/data/Btag.bam',
    })
    await b.getHeader()

    const features = await b.getRecordsForRange('chr1', 980654, 981663)
    // ZC:B:i,364,359,1,0    ZD:B:f,0.01,0.02,0.03   ZE:B:c,0,1,2,3  ZK:B:s,45,46,47
    const ret = features[1].get('ZD').split(',')
    expect(features[1].get('ZC')).toEqual('364,359,1,0')
    expect(features[1].get('ZE')).toEqual('0,1,2,3')
    expect(features[1].get('ZK')).toEqual('45,46,47')
    expect(+ret[0]).toBeCloseTo(0.01)
    expect(+ret[1]).toBeCloseTo(0.02)
    expect(+ret[2]).toBeCloseTo(0.03)
    expect(features.length).toEqual(2)
  })
})

describe('BamFile with paired ends', () => {
  it('paired ends', async () => {
    const b = new BamFile({
      bamPath: 'test/data/paired.bam',
    })
    await b.getHeader()

    const features = await b.getRecordsForRange('20', 62500, 64500)
    const f = features[0]
    expect(f._next_refid()).toEqual(19)
    expect(f._next_pos()).toEqual(62352)
  })
  it('read as pairs', async () => {
    const b = new BamFile({
      bamPath: 'test/data/paired.bam',
    })
    const p = new BamFile({
      bamPath: 'test/data/paired-region.bam',
    })

    await b.getHeader()
    await p.getHeader()

    const features = await b.getRecordsForRange('20', 62500, 64500, {
      viewAsPairs: true,
    })
    const features2 = await p.getRecordsForRange('20', 0, 70000)
    //    expect(features.length).toEqual(features2.length)
    expect(features.map(f => f.get('name')).sort()).toEqual(features2.map(f => f.get('name')).sort())
    const f = features[features.length - 1]
    const f2 = features2[features2.length - 1]
    expect(f.get('start')).toEqual(f2.get('start'))
  })
})

describe('BamFile+CSI with large coordinates', () => {
  it('use csi', async () => {
    const b = new BamFile({
      bamPath: 'test/data/large_coords.bam',
      csiPath: 'test/data/large_coords.bam.csi',
    })
    await b.getHeader()

    const features = await b.getRecordsForRange('ctgA', 1073741824, 1073741824 + 50000)
    expect(features.length).toEqual(9596)
  })
})

describe('Pair orientations', () => {
  it('test pair orientations', async () => {
    const b1 = new FakeRecord(true, 'F', 'F', 100)
    const b2 = new FakeRecord(true, 'F', 'R', 100)
    const b3 = new FakeRecord(true, 'R', 'R', 100)
    const b4 = new FakeRecord(true, 'R', 'F', 100)
    const b5 = new FakeRecord(false, 'F', 'F', 100)
    const b6 = new FakeRecord(false, 'F', 'R', 100)
    const b7 = new FakeRecord(false, 'R', 'R', 100)
    const b8 = new FakeRecord(false, 'R', 'F', 100)
    const b9 = new FakeRecord(false, 'F', 'F', -100)
    const b10 = new FakeRecord(false, 'F', 'R', -100)
    const b11 = new FakeRecord(false, 'R', 'R', -100)
    const b12 = new FakeRecord(false, 'R', 'F', -100)
    expect(b1.getPairOrientation()).toEqual('F1F2')
    expect(b2.getPairOrientation()).toEqual('F1R2')
    expect(b3.getPairOrientation()).toEqual('R1R2')
    expect(b4.getPairOrientation()).toEqual('R1F2')
    expect(b5.getPairOrientation()).toEqual('F2F1')
    expect(b6.getPairOrientation()).toEqual('F2R1')
    expect(b7.getPairOrientation()).toEqual('R2R1')
    expect(b8.getPairOrientation()).toEqual('R2F1')
    expect(b9.getPairOrientation()).toEqual('F1F2')
    expect(b10.getPairOrientation()).toEqual('R1F2')
    expect(b11.getPairOrientation()).toEqual('R1R2')
    expect(b12.getPairOrientation()).toEqual('F1R2')
  })
})

describe('SAM spec pdf', () => {
  it('check parse', async () => {
    const b = new BamFile({
      bamPath: 'test/data/samspec.bam',
      baiPath: 'test/data/samspec.bam.bai',
    })
    await b.getHeader()

    const features = await b.getRecordsForRange('ref', 1, 100)
    expect(features.length).toEqual(6)
    expect(features[2].get('sa')).toEqual('ref,29,-,6H5M,17,0;')
    expect(features[4].get('sa')).toEqual('ref,9,+,5S6M,30,1;')
  })
})
describe('trigger range out of bounds file', () => {
  it('range error', async () => {
    const b = new BamFile({
      bamPath: 'test/data/cho.bam',
    })
    await b.getHeader()
    expect(Object.keys(b.chrToIndex).length).toEqual(28751)
  })
})

describe('test too large of genome coordinates', () => {
  it('test error', async () => {
    const ti = new BAI({
      filehandle: new LocalFile(require.resolve('./data/needs_csi.bai')),
    })
    await expect(ti.parse()).rejects.toThrow(/too many bins/)
  })
})

describe('large indexcov', () => {
  it('human 1000g', async () => {
    const ti = new BAI({
      filehandle: new LocalFile(require.resolve('./data/HG00096_illumina_lowcov.bam.bai')),
    })
    const ret = await ti.indexCov(10, 0, 1000000)
    expect(ret).toMatchSnapshot()
    const empty = await ti.indexCov(0)
    expect(empty).toEqual([])
  })
})

// we cannot determine duplicates as unique because we require dehashing
xtest('unique id for duplicate features', async () => {
  const ti = new BamFile({
    bamPath: require.resolve('./data/exact_duplicate.bam'),
  })
  await ti.getHeader()
  const ret = await ti.getRecordsForRange('ctgA', 0, 1000)
  expect(ret[0].id() !== ret[1].id()).toBeTruthy()
})

test('usage of the chr22 ultralong nanopore', async () => {
  const ti = new BamFile({
    bamPath: require.resolve('./data/chr22_nanopore_subset.bam'),
  })
  await ti.getHeader()
  const ret1 = await ti.getRecordsForRange('22', 16559999, 16564499)
  const ret2 = await ti.getRecordsForRange('22', 16564499, 16564999)
  const findfeat = k => k.get('name') === '3d509937-5c54-46d7-8dec-c49c7165d2d5'
  const [r1, r2] = [ret1, ret2].map(x => x.find(findfeat))
  expect(r1.getReadBases()).toEqual(r2.getReadBases())
  expect(r1.getReadBases()).toBe(
    'TCTTCAGACCCTCGAAACAGTGTTCTGAAATCCTATGGCAGGGAACAACAGAACCCAGCCACTGTGTGCTGGAATCCTGTCTGAGGACAAACATTCAAACACTCATGAAAGTGTTCTGGAATCTTATGTGAGTGATAAGCAATCAGAAACCAGCAGCGGTGCTCTGTAATCCTTTGTGAGGACAAACAGTACACAGAGCAAGTTCTGGAGTTCTATGTGAGGGACAAACTCTCATGACAGCAGCAGTGTTCTGGAATCACTTGTGAGGGCCAAACACTCAGACTTATGCAGCAGTATTTACAGATCTTATGTGTGATGGAAAACACTCTGAACCCAGCAGCAGTGTTCTGGAATCCTATATGAGGAAAAACTCAGAACCTGCAGCAGTGTTCTGGAATCCTTAGTGAGGAGGTATTCAGAACCTCATATCAGTGTTATGGAATCGTATGTGAGGACAAACACTCTGAAACCAGCAGCAGTGTTCTGGAATCCCATGTGAGAGACAAACACGAGAATCCAGCAGCAGTATTCTGGAATCCTATGTGTGAAAACACCCAGAAACCAGCAGCGTAGTACTGGAAGGAAATCTTTGTTAGGGGCTAACATTCAGACACAAGCTGTATTCTGGAATCTATGTGAGGACAAACACTCCTATCAGTAGCAATGTTCTGCAATTCTTTAGCAGCAGACAACATCTTCAGGCCCTCATGCAGCAGTTTCAAAAATTCCACAAGAGTGAGAGATTAAACACTCCAGAACCCAGCAGAAATGCAGGGATCTATGTGAGGGCAAATACTTGGAATCCAGCAGCACTGTTCTTGAAACCTATGTGAGGGACAAGCACTCACAACAGCCACTGTGTACCAGAATCCTATTTGATTGTCAAACACTTCAGACCCTAGTAGAGGAGTGTTCTGGAATCCCTATGTGAAGGACAAACTCTAAATAACCAGCATAGCAGTGCTCTGGAATCTTTGGGAGAGAAAGCATCAGACCCTAGCAGTGTTCTGGGATCCTATGTGAGGGAAAAACATTCCAGACCCGCATAGCAGTGTTTGGAATCTATACGAGTGACAAACACTCAGAACCCACCAGCAGTGTTCTGAATCTTTTTGTGAGGTAAAAACACTCAGACCCTCAAAGCAGTGTTCTGGAATCCTGCGTGATGGAAAAACATTCAGACGTAGCTGTGTTCTGGAATCCTATGTGAGGGAGAAACATTGTGACCCTCATGTAGCATTGTTCTGGAATCCAATATGAGGGACAAACACTCAGAAGCCAGCAGCTGTATTCTGGAATGCCATATTGAGAAAAGACTCCAGAACCCAACAGCAGTGTTCTGGAGATCTATCAAGGAAATAACCCTAGAGATTGGAGCACTGTACTGGAAGTCTTATATTAGGGACACATATTCAGACACTCGTAGAAGTGTTCTGGAATACTATGTGAAAGGACAAACACTAAGAAAACAGCAGCAGGGCTTTGGAATCCTTTGTGAGGACAAAAAAACAGAACCCATCAGCAGTGTTCTGAGAATCATTGTGAGAAAAATGTTTCTAGGTCCTATTAACAGTGTTCTGGAGATCCTATGTGAGGTAAACATTCAGATCCCTCATAGCAGTGGTCTGGAATCGTATGTGAGAGACAAACCCTCACAACCCAGCAGCAGTGTTCTGCAATCCCTATGTGAGCGACGAACATTGAGAACTTCGTAGCAGTGTTCTGATATTCTATGTAGAGCAAACACTCACAACCCGGCAGCACTGCTCTGGAATCGTATGTGAGGACAACAACAGAACCCAGCAGCCGTGTTCTGGAAACCTCGTGAGGGACAAAATCTCAGAGCTCAGCAGCAGTGTTCTGCAATCCTATGTGAGTGACAAATACTCAGAACCCAGCAGCAGTGTTCTGGAATCTTTGTGAGGACAAACACTAGAACCCAGCAGCAGTGTTCTAGAGTCCTTTGTGAGGACAAACATTCAGAAACTCTCTTCCAGTGTTCTGGAATCTTAGGTGAGGGACAAACACACTGAACCCAGCAGCTGTTTTGGAATCCCATGTGAGGCAGAAACACTCAGAACTCAGCAGTGTTCTGGAATCTATGTGAGTGAAAAACACTCAGGAGCCAACAGCAGTGTTCACAGAATCTTTGTGGGCAAACCTTCAAGACCCTAGAATCAGTGTTCTGGAATCCTATGTGATGAACAAACACTCAGAACCCAACAGCAGTGTTTTTGATTCCTTTGTTTTGGAGAAACATTCAGACCATTGTAGCACTGTTCCACTATTCTATGTGAGGGACAAACTCTCAGAACCCAGTAGCAGTGCTAAGTCCTATGTGAGGACAAACACTCAGAACCCAGCAGCAGGGTTCTGGAATCCTATGTGAGGGTCAAGCACTCAGAGGCAGCAGCAGTGTTCTGGAATCCCTATGTGAGGGCTTACTAAGAACCCAGTCACTGTGTGCTGGAATCCTATGTGGGAGAAACATTAGAGACAGTCACTGTGTGCTGGAATCCTATCTCAAGGACAAACATTCAGACCATTGTAGCACTGTTCCGCTATCCCTAGCGAGGGACAAACTCTCAGAACCCAGTAGCAGTGCTCTAGGAATCCTATGTGAGGACAGAAACACTGAACCCAGCAGCAGCAGGAATACTGGAATCCTATGTGAGGTCAAACACTCAGAAGGCAGCAGCAGTATTCTGGAATACATGGCAGGAGAAACATTCAGAACCCAGTGCTGTGTGCTGGAATCCTATGTGAGGGGAGAAACACTCACAACTCAGTCACTATGTGCTGGAATCCTATCTGAGGACAAACATTCAGACATGTAGAAGTGTCCTGGAATCCTATGAGGGACAAACACTGAGAACCCAGCAGCAGAGTTCTAGAATTCTTCGTGAAGACAAACATTCAGACACTCGAAGCAGTGTCCTAGAATCTATGTGAGGACAAACACTTCTAGAACCCAGCAGAATTGTTCTGGAATCCTTTGTGATGGATGAGCATTTGAGCCCTCGTGGCAGTGTTCTGGAAACCTAAGTGAGGGCAAACACTCAGTTGTAGCAGTGTTCTGGAATCCTATGTGACTGACAAACACTCAGAACCCTGAAGCAATGTTATGAAATCCTGTGTGAGTGCAAACACTCAGAACCCACCATCAATGCTCTGCAATCCTATGTGAGGAAAGAAACACTCAGAAACCTGCAGCAGTGTTCTGGAATCTATATATGGGTCAATAATTCAGACCATCATAGCACTGTTCTGGAATGCTCTGTGAGGACAAACATTCAGAAACTTGTAGCAGAGTTCTGGAATCTATGTGAGGGAGAAACCCTCAGAACCTAGCAGTAGTGTTCTGGAATCCTTATGTGAGATAACACTCAAGACCAGCCGCAGTGTTCTGGAATGCTATGTGAGGACAAACACTCAAAACCAAGCAGCAGGATTCTGTTATCTACCATGAGACAAACACTCGAACCCAGCAGAACTGTTATGGAATCTATGTGAGGACAAACACTCACAAACAAGCAGCTTTTGGAATCCCTATGTGAGGAGAAATCTTCAGAACCTAGCAGCAGTGTTCTGGAATCGTATGTGTGGACTTCAGCACACTCAGAACCCAGCAGCATGTTGAGAATGCTATGTGAGGGAGAAACACACAAAACCCACCAGCAGTGTTCTGGTTTAATATATGCGGGACAAACACACAGAACCCAGCAGAAGTGTTCTGTAATCCCATGTGAGGGTCAAACACTCACAAACCAGCAGCAATGTTTTGGAGTCTCTTTGTGAGGGACAAACATTAAACCTCAATAAAGTGCTCTGCAATCTATCAGCGAGGAACAACACTCTACAGGCCCAGCAGCAATGTTTTCGAATCCCATGAAAGGGACAAACACTCAGAACTTCGGCAGCATTTTCTGGAATCCTATGGTGACAAACTCTCAGAACACAGCAGCGGTGTTCTAGAATCACTGTAGGAGACAAACATTCAGAATGATCATAACAGTGTTCTGGTATCTCATGTGAGGACAAACACTCGGAAACCAGCAGCAGTGCTCTGAATTCTTGCAGGACAAACAAACCGAAGAGGTTCTGGAATTACTGTAAAGGACCAAGCACTGAGAACCCAGGAGCAGCGTTCTGGAATCCCATGTGAGGGACAAACGCTCAGAACCCAACAGCAGTGTTCTGTAATCTAATTGAGGACAGACACTCACAGCCCAGCATTGTTCTAGATTCGCTGTGAGGAACCAAGCATTTCAGACCCTCGGCAGTGTTCTGGAATGTTATGTGAGGGACAACCCTCTGAACCCAGCAGGGTTCTGGAATCAGTGAGTGACAAACACTCAAAACCCAGCAGCAGTGTTCCGGAATCCTTTGTGAGGACAAGCTTTCCAAACCTCGAAGCATTGTTATGGAGTCACCTTAGCAACGAGGAACACACTCAGAATCCCGCGCGCAGCGATATGATCTTGTGATGGACAAACATCCAGACACTCTTAGCAGTGTTCTGGAACGCTATGTGATGATTGTAAACCTACAGGCCAGGCAGTGTTCTGGAATCCTCTGTGAGGACAAACACTCAGAACCCAGTAGTAGTGTTCTGGAATCTAATGCATGAGGACAAACACACTAAGAACCCAAGGAGCAGTGTTCTGCAATCTATGAGGGACAAACACTACAGCCCACCAGCATGGCAGTGTTCTAGAATCCTTTGTGAGGAAAAACATTCAGACCATCGAATCAGTGTTCTGGAATCTATATGTGGGGAGACAAACGCTCAGAACCCAGCAGCAGTTTTCTGATCCTTTTCAGACAGACAAACCTTTAGACGATCTTAGCAGTGTTCTGTTATCTATGTAAGGGACAAACACTCAGAACCCAGCAGCAGTGCTCTGGATTCCTTTGTGGGGACGAGCACTTAGAACCCAGGAGCAGTGTTCTGGAATCCTATGTGAGGACAAACACTCAGAATCCAGCAGCAGTGTTCTGGAATCTTAGAGTGAGGACAGACACTCACAACCCAGCAGCAGTGTTCTAGAATCCTTTGTGAGGGACAAACAGCATCAGACCACAGAAGCAGTGTTTCTGGAATCTATGTGAGAGCAAACACTCAGAGACACAGCATCAGTGTTTCACAGAATCCTATCTTGAGTGACAAACTAGAACCAGAACAGTATTCATCCATTGTAGAGGACAAACATTCTGTCTCAGCGAAGCATTTTTCTGGATTCCTATGCTGAGGGACACACTCAGAACCCAGCAGCAGTGTTCTGGAATCCTATGTGTGGGACAAACACTCAGAAACCAGCAGCAGTGTTCTGGAATCCTACCGTGAGGGACAAACACTCAGAACACAGCTACTCTGTACTGGGAATCTATCTGAGTATTGACAACATTCAGACTCTTGCAGAAGTGTTCTGGAATCCTATGTGATGGACAAACACTAACAAACTAGCAGCAGCGCTCTGGAATTCTTTGTGATACAGACGTGTTCAAGGAGCTCTTTAACAGTGTTCTGGAATCGTATGTGAGTACAAACACTCAAAACTCAGCAGCAGTGTTCTGGAATTCTATTTGAGGACAAACTCTCAGAACCCAGCAGCCATGCTGTGAAATGATATGTGGACAGACACTCAGAACCCAACAGCAGAGTTCTGGTATCTAAGTGAGGAACAAACACTCAGAACCCTGCAGAAGTATTCTGGAATCATGTGAGGGACAAACACTCAAAATCCAAGAAGGCAGTGTTCTGGAATCCTATGTGAGGACAAACACTCACACCCTCGAAGTGTTCTGGAATCTATGTGAAGGACAAACACTCAGAACCCAGTAGCAGTGTTCTGGAATCTGGTGTGAAGGACAAGCGTTCAGACTTGCTCGTAGCAGTGATATGGAGTTGCTGTAGAGACAAGCATTCCAGACACACTTATGTTCTGGAATCCTAAGTGAGAGAAACCCTCAAAAACAAGCTGCAGTGTTCTAGGAAATCTATGAAAGGACAATCCCTCAGTATCGAGGCAGTGTTTGGAATCCTATCTGAGGGACAAACACTCAGAACTCAGCAGCAGTGTTCTGGAATCCTGTGTGAAGGAGAAACACTAGAACCCAACAGCAGTGTTCTGATTCCCGAAGTGTGGGACAATCACTCAAAACCCAGCCACTGTGTTCTGGAATCCTATCTGAGGTCAATGTAGGAACCTCGAGGAAGAGTTCTGGAATCCTATGTGAGGGAAAACACTCTGAAACCAGCAGAAGTGTTCTGGAATCCTTTGTGAGGGACAAACACTGAGAAATCAGAGCCGTGTTCTGGCATCCTATGTAGCGACAAACACTCTGAACCCAGCAGCAGTGTTTTGAATCACGTGAGCGACAAACACTCAGAACCCAAAGCAGTGTTCTGGAATACTTTTTGAGGACAATCATTCAGAACCTTGTAGCTGTGTTTCTGGAATCATATGTGAGGGCCAGCGAACACTTTGAACCCAGCTGCAGTGTTTTTGATTCCCCTGTGAAGGGAAAAACACTCAGGGCAGCAGCAGTGTTCTAGAATCAGCGTAATGGGACTAACATTCAGACCCTCAACGGTAACTTTTGGTCTATGTGAGGGACAAACACTGAGAACCCAACTGCAGTATTCTGCAATCCTTTGTGACAGAGAAACACTCAGACCATCGTAGCAGTGTTCTGGCATCCTATGTGCAGGAAAAACACTCCAAGAAACCAGCATCAGTGCTCTGGATTCCTTTGTGAGGGACAAACAAACAGAACCAGCAGCAGAGTTCTGGAATCCTATGTTGAGGACAAACACTCCAGAACCCATCAGCAGTGGTCAGAAATAATTTGAGGACAAACATTCAGAACCTAGTAGCAGTGTTCTGGAATAGTATGTGAGGACAAACACTCTAGGCAAACTGGCAGTCTTTTGGAATCACACGTGAGGGACAAAAACTCCAGAACCAAGCAGCAATGTTCTGAATACCATGTGAGAGACAACACTCAGAGCCCAGCAGCAGTGTTCTGGAATCTTATTTGAGTGACAAACACTGAGCTTAGCAGCAGAGTATTTACAGAGTCCTTTATGAGAACAAACTTCAGACACGCAGTCTTAAGATCCTATGTGAGAGACAAACCCTCAGAACCTTGAAGCAATGTTCTGCAATCCTTTTTGTTGGACAAACATTCCAGACCCTCGTAGCAGTGTTCCAGAATCCTATGTGGCGAAGGAACAAACACTCAGAACCCAGCAGTAGTGTTCGGGAATCCTATGGGAGGGACAACCATTTCCAGATCCAGCAGCAGTGTTGTGTAGTCTGTGAGGACAAACACTTTCAGAACCCAGCAGCTGTGTTCTGAAACCTATGTGAGGAAAATCATGAACCCAGCGTGTTGTGTTCTGGAATCCTATCTGAGGGAGAAATATTCAAACACTGTAGAAGAGTTCTGGAATCCTATGTGAGGGAAAAACCCTCAGAAGCCAGCAGTGCTCTGGAATCCTTTGAGCAAACAAATCAGAACCCTAGAAGCAGTGTTCTTGGATCTTTCCAGCTAGGAAAAACAGCTTCAAGACCCTCATAATAGTATTTTGGAATCCTATCTGAGGGACAACACTCAGACCAGCAGCTGTGTTCTGGAATCCTATATTATTAAGATAAACACTTAGAACCCAGCACAATATTCTGGAATACTACGTGAGCGACAAACTTTCAGAAGTTTGTAGCAGTATTCTACAGAATTCTATGTGAGGGACAAACACACAAGGCCAACAACTTGATAAGTGGTTCCTAAGTGAGGACAAACATTCAGAACCCAGCAGCAGTGTTCTGGTATCCTATGTGAGGACAAACACTCAGAACCCAGCAGCAGTGTTCTACAGAAATCCCTTTGTGAAGAGAAAAATGGCAGACCCTGCGCAGTGTTCTACTGGAATCCTATGTGATAGAAAAGTTCATACCCTCATAGCAGTGTTCTGGGATCCTATATGAGGTTGGCTTACAGAACCCACCAGCAGCGCTCGGAAACCACACTCTCTAGTGTTCTTGAATCCCATGTGAGAGAAACCTTCATACCCTCGTAGCATTGTTCTGGAATCAATATGAGGACAAACACTCAGAACCAGCCCAACATTCTGGAACCTTTATTGAGGATAAACATTCAGACCGTCATAGCAGTGTGCTGGAATCCTATGTGAGGGACAAATGCTCGAACCCAGCAGCAGTGGACTGGAGTCCTATGTGAGGACAGTACTCTGAGCTTAGCAGCAGTGTTCTGGAATCCTCTGTGAGGGACAAACTTTCACAACTGGCAGTGTTCTGGAGGCTTGTGAGTACAAACATTCAGAACCCAGCAGTGTTCTGGAAGTCCTTTGTGAGAACATTGTTGGAACCTCATAGCAATGTTCAGGGAGTAGGCGTACGTAAGGGACAAACACTCAGGAACACAGCAGCAGTGTTCTGCAATCCCATATGGACAAACACTCGAACCCAGCTGCAATGTTCTGTAATCCCTGTTTGACGACAAAGGCTCAGAAACCAGCAGCACTGTTCAAGAATCCTTTTTTGTGTGACAAACATTCTGAACCTCTAAAAGCAGTGTTCTGGAATCCTACTGTGAGGACAAACACCACAATCCCTGCAGCAGTTTTCTGGAATCCTTTGTGATGGACAAACATATTCAGACCCTCGTAGCAGTTTTCAGAATCCTATGTGTGGGACAAACACTCAGAACACAGCAACAGTGGTCTAGAATCCTTTGTGTGGGACAAAGATTCAGAACCCAGCAGCAGTGTTCTGGAATCCTATCAGGTACAAACACTCAGAAACAGTACAGCTTGTACTTTTGGATTCCACTGTGTACTGGAATCCTATCTGAAGGAAAAACATTCCGAACTTCGTAGAAGTTTTGGAATCCTGTGTGACGGACAAACACTAGAAATCTGCAGCAGTGTTCTAGAATCCTTTCTGAGTGACAAACAAACAGAACCCAGGAGCAGTGTGCTGCTATCCTTTTGAGGAAAAACTTTCACATCCTTATAGCAGTGTTCTGAAACCTATGTGAGGAAAGAAATTCAGACCCTCGTAGCAGTGCTCTGGAATCCTATATGAGGACAAACACTCAGAACCCAGCAGCAGTCTTCTGGAATCCTTTGGAGGAAAAACATTCACACCCTCGTAAAAGTGTTCTGGAATCTGTGAAGGAAAACATTCAGACCCTCGTAGCATTGTTCTGGAATCTAATATGAGGACAAACAGTCAGAACCCAGTTGCAGTGTTCTGGAATACTATGTGAGTGACAACACTCAGAACCCAGGAACTGGGTTCTGGAATTGTCTGTGCGGGCCAGTCATTCAGAACCTCATTATGATATTTCTGAGTCTATGTGAGGGAAAAACACTGTGATCTCAGCAGCAGTGTTCTGGAATCTATGTGAGGGCGAAACCTCTGACCAGCAGTCGTGTTCTGGAATCCCATGTGAGACAAACACTGAGATCTAGCAGCCTGTTCTGAATCCTATGTGAGTACAAACTCTCAGAACCCAGCAGCAGTGTTATGGAGTCCTTTGTGAGAGACAAACATTCAGACCCTCGTAGCAGTGTTCTGGAATCTTGTGAGGCACAAACACTCACAGCAGTAGACCCTCGTAGGAGTGTTCTGGAATCTACGTAAGGGACAAACACTCAGAACTCAGTGATTATTTTCTTGAAAGCTAAGTGAGTACAAACACTCGAAACCAGCAGTGTTCTGGGAATCTTGGTGAGGACTAACACTCCAGAACCCAACAGCATGTTCTGGGAGTATATGTGAAACAAGAACTCAAGAACTCAAACAGTGTTCTGGAATCGTATGTGAGGAACAAGCAATCAGGGCCAGCAGCAGCAGCCATGGAATCCTATGTGAGGGACAAACACTCAAACCCAGCCACTGTGTTCTGGAAACCTATCTAGTGATGACAAACATTCAGACACTCGTGGAAGTGTTCTGGAATCCTCGTGAGAGGCGGCTCAGAAACCAGCATAGGTGTTCTGGAATCCTTTTTGTGGAGAAACAAACAGAACCCAGCAGCAGTCTTCTGGAATCTATGTGAGGGAAAATATTTAGAACCCCGTAGCAGTGAAATACCTGGAATTCTATGAGGACACAACACACAGGACCCAGCAGCAGTGTTCTGGAACCTTATGTGATGGACAAACACTGAGAACACAACAGCAGTGTTCTGAAATCACATGTCAGCAGAAAAACATTCAGAAATTCATAGCAGTGTTCTGGAATCCTTTGTGACAGACAACACTCAGACTGTCGTAGCAGTGTTCTGATTTCCCATGAGAACAAACACAGCTAACATGTCTCAAAATCTCATGGGATCTATGCAAGGAACAACACAAGAGCACCCACACTATGTTCTTAAATACTAAAGAAACAACTTATTCAAACACTGGCCAAAGTATTCTAGAATCTATGTGAGGATAAACACTCAGAAACCAGCAGCAGTATTCTGGAATCCTTTGTGAGGGAAAAACATTAGACTCACGCATTCTTTAAAAATCTCTGTGTGAGGGACAAACCGTCTGAACTGAGCAGCAGTGTTCTGCAATCACTCTTGAGAGACAAACACTCACAGACAGCAGCAGTGTTCTGAAATCTAAATGAGGAACAAACCCTCAGAGACAGCAGCAGTGTTCTGAGTCCTTGTGGGGTACAACATTCAGAACCTCGAAGCAGTGTTCTGGAATCTATTTGAGGACAAACTCACAGAACCCAGCAGCAGTATTCTGGAATCCCAAGTGAGGGACAAACACTCAGAAACCAGCAGCAGTGTGCTGGAATGCTTTGAGGACAACATTCAGACCTTCGAAGCAGTGTTCTGCAATCCTATGTGATTGACAACTCTCAGAACCTAGGAGCAATCTTCTGTAATCTGTTGTGATGGAGAAACATTCGGAACCTCTTCGCCAGTGTTCTGGAATCTAGGTGTGGGAGAAACACTCAGAATCCAGCAGCAATGTTGGAAGTCTCTGTGAGAAAACACTCAAGGCTCAGCAGCGTAGTGTTCTGGAATCCTATGTGACCAGACAAACACTCAGATCACTGCAGCAGGGGGTCTGAAATCCTATGTGAAGGATAAGCACTCAGAACCCAGGAGCAGCGTTCTGGAATCCTTTCTGAGGACAAACATTCAGAACCTCGTAACAGTGTTCTGGAATCTTATGTGAGGACAAACACTCAGAACCCAACTTGGCAGCATTGTTCTGGAATCTTAGATGTGGGACAAACACTCCAGAACCAGGCATTAACAGTTCTGGAGTCCCATGTGAGGACAAACACTCAGAACCCAACAGCAGTATTCTGGAATCCTATGTGAGTGACAAACACTCAGAATCCAGCAGCAGTGTTCTAGAATTCTTTGTGTGGGACAAGCTTCATGCCCTCAAAGCAGTACTCTGGAATCCTATGTGAGGGAGGAACAGTCACAACCCAGCAGCAGTGTTCAGGAATCCTTTGTGACTGGACAAACATTCAGACCGTCGGAGCAGTGTTCTGGAATCTAAGTGAGGACAAACTACTCAGAACCAAGCCACTGTGTTCTGGAATCCTTCTGAGGGACAAATATTCAGACACCGTGAGTGTTCTGGAATCTATGTGAGGACAAACACTCAGAAAACAGCAGCAGTGCTATGGAGACCTTTGTGAGGAGCAGCAAACACAGCCAGAGTTTTATTCTGTAACCTTTTTGAGAGAAAACATTCAGAACCCCGTAGCAGTGTTCTGGAATCTATGTAGGGGACAAACATTCAGAACCCAGCAGCCGTGTTTTGGAATCCTGAGTGAAGACAAAGATTCAGAACTTCATAGCACTGTTCTGGAATCCCAGCTGAGACAGAAACACTCAGAACCCAGCAGTGTTCTAGAATCTATGTGAAGACAAACCCTCAGAACCCAACAGCAGTGTTCTGGAATCCATGTGAGGGACAAACACTCAGTACCCAACCACTGTGTTCTGGAATCCTATATGAAAAGGGACAAACATTCAGACAATCGTAGAAGTGTTCTGGAATCCTATATGAGGACAACACTCAGAAACCACCAGCAGTGCTCTGGAATCTTTTGTGAGGACAAAAATCTGAACCCAGCAGCACTCATTATTCTCTAATCATTTTAGGGACAAACGTTCAGAACCTCGTAGGAGGTTCTTGAATCTAAGTGAGGATAAAGCCCAGGCAGCAGCAGTGTTCTGGAATCTGCGTGAGTGACAAACACTCCGAACCCCGCAGGAATGTTCTTGAATCCTTTGTGAGGGACAAACATTCAAACCCTCGAAGCTATGGTGCTATGGAATCTATACATGAGGTACAAACAGTCATAACCCAGCAGAAATCTTCTGGAATCCTTGTTATGGACAAACATTGAGCCCTTGTAGCAGTGTTACGATCTAATGGAGGCACAAACACTCAGAACCCAGCAGCAGTGTTCTGGAATCTTATGTGAGGGACAAACACTGCAATCCAGCAGAAGTGTTCTGGAATCCTATCTGAGGACATACACTCAGAACCCAGTAGCAGTATTCTGGAATTCTATGTGATGGTACACGCTCAGAAACCAACAGCTGTTTTCTGGAATCTTGTCCAGTGACAAATATTCAGACACTCGTGGAAGTGTTCTGGAATCCTATGTGAGGGATAAACACTCAGAAACTAGCAGCGGTGATCTGGAATCCTTTGTAGAGGCTCAACAGAACCCAGCAGCTGTGTTCTGGAATCTTTGTGAGGAAAAATATTTAGACCCTTGTAGCAGTGTTCTGGAATCTATGTGAGGGACAAACACTGATACAACCCAGCGGCAGTGTTCTGGACTCCTCTATGAAGTCAAACCCTCAGAACCCAGCAGCAGTTTTCTGAAATAAAATGTGAGCAACAAACATTCAGAATTTCGTAGCAGAGTTCTGGAATCCTAGCGAGTGACAAACACTCAGGGAAACCAGCAGCAGTGTTCTAGAATCCTTTCTGTGGGACAAACTTTCAGACGCTCAAAGCAGTGTTCTGGAATCCTATGTGATGGACAAACACTCCGATCCCATCAGCAATGTTCTGCAATCCTTTGTGATGGGCAAACATTCAGACCCTCGTAACAGATTTTGGAATCTAAGTGAGGGACAAACACTCCAGAACCCAGCAGCAAGCAGTGTTCTAGAATCCTATATGAAGAACAAACACTCACAACCCAGCAGCCAGTATTGCTAATCTGTTTGAGGGACAAACACTCCAGAACCCACTCACTGTGTACAGGAATCCTATCTACCATGGGCTAACACATTCAGACCCTCGTAGCAGTGTTCTGGAATCCTATGTGAGGAGAAACTCTAAAAAACCAACAGCAGTGCTCTGGAATCCTTTATGAGGGAAAACATTCAGACCTTTAGCAGTGTTCTGGAATCCTATGTGAGGGAAATATTTTCAGAGCCTCATAGCAATGTTTCTTAATCATATATGAGTGACAAACGCCAGAAACCAGCAGCAGTGTTCTGGAATCCCTTGAGAGGGAAAAACATTTACACCTTCATAACAGTGTTCTGGAATCCTTACTGTGGGAAAAATATTCAGACCCTCGTAACAGTGTTCTGGAATCCTATATGAGGGACAAACACTCAAAACCAGCAGCAGTGTTCTGGAATCTATAGCCAGAGAAGCGTACTCAGAGCTGTACAGTGTTCTGGAGTCTATGGAGTGACAAACTTTTGAAATTCGCTGGCAGTATTCTGGAATCTTATGTGAGGACAAACACACAGAACCCAGTAGCAGTGTTCTGGAATCTTATGTGAGTAACAAACACTCAGAATCCAGCAACAGTGTTCTGGAATCCTATGTGAGGACAAACACTCCAGAACTAGCAGCAGTGTTCTAGGAATACTTTGTGAGGAAAAACACTCAGAACACAGTAGTGTTCTGGTATCCACTATTATTATAGAATCCTATCTGAGACAAACATTCAGAACCTAATAGTAGAAATGTTGCAATTCTACGTGAGGGACAAATACTAAGAAATCTGCAGCAGTGCTCTGGAATCTATTGTGAAGGTCAAACAAATAGAACCCAGTAGCCTTGTTCTACAATACTTTATGAGGAAAAACTTTCAGACCCTCATGGTGGTCTGGAATCACACGTAGGAACAAACACTCAGAGACAGCAGCAGTGTTCTGTACTCCTTTGTGAGGACAACATTCAGTTCCTCAGAGCAGTATTTGGAATCCTATGCTTTGAATGACAAGCACTAAGAAACCATCAACAGTGTTCTGGAATCTATGCTGAATGACAAACCTAAGAAACCATCAGCAGTGTTCTGGAATCCTTTGTGAGTAGCTAAACATTCGACCCCCTTAGCAGGGTTCTGGAACTATGTGAGGACATTCAGACACTTAGCAGTGTTTTGGCGCCTTAGCAGTGTTTGGAAACCAATGTGAGGGCCAAACAGTCAGAACCCAGCATCAGTGTTCTGGAATACTTGGTAAGGGACAAGCATTCAGAAAATCTTATCAGTTTTCTGGAATCCCAACTGAGGAGAAACGCTCCAGAAAATATCTGCAGTGTTCTAGAATTCTATGTGAGGACAAACCCTCATTGCGAGCTGCAGTGTTCTGGATTCCCTAGGTGAGGGACAAACACTCCAGAACAAAGCAGCAGTGTTCACAGTCTCATAACGATGGACAAAAACTCAGAACCCAGCAGTGTTCTGATACCTATGGGAGGGACAAACACTCAGAACCCAGCCCCTGTGTTCTGGAATCCTATCTGAAGGACAAACATTCGGAGACTTGAAGAAGTTTTCTGGAATCTATGTGAAGGACAAACAGTCAGAAACCTGTAGCAATGTTCTGGAATCATTTGCAGGAACAAACACTCAAAACTCAAAAGCAGTATCCTGGAATCCTACGTGAGGCCCAAGCCTAAGAACCCAGCAGCAGTATTTTCGAATCCTTAATGAGTGACAAACAGTCCAGAAACTTGCAACATTATTTTAGGTTGCTGTCTCTAGTACAGAGTTCTGGCCAAGAACAAACGCCAGAACAACCACTGTATTTCACAGAATATTGCTCTGAGAAAAAATAGCCGAGCCTCGTAGAAATTATTTCACAGAATCCCTATGGTAACCAAATACTCGAAAACCGCTCAACAGTGCTCTGGAATCCTTTGTGATGGATAAATAAACAGAGCCCAGCAGCAGTGTTCTGGAATCCTTCGTGAGGACAAACATTCAGAACCTTGTAGCCGTGTTCTGGAATCGTATGTGAAGGGTCAAACACTTTGAACCAGCAGCTGTGTTCTGGAATCTCTATGTGAGGGACAGAAGCACTAGAACCCAGCAACAGTGTTCTGTAATCCTTACTAGTAGAGGACAAAGCACAAGAGCCTTAGCATTGTTCTGCAATCCTTTGTGTGGGGACAAAACACTCAGGCCCAGCAGCAGAGTTGAATCCCATGTGAGGGACAAACGTTCAGGCACTCAGAATAGTGTTTGGAATCCTATGTTAGGGACAAACACTCAGAAAACTGCAGCAGTGTTCTGGAATCACACGTGGGGATGTGACTGAATCCTGATAGCACTGTTGTGGAATGCTCTGTGAGGAACAAACAATCAGACCCTCATCAGCAGTGTTCACAATCCTATGTAAGTACAAACCCTCACAACTCAACTAACTTTCTGGAATTCTATGCGAGGACAAACTCAGAACCTAACAACTTGTTCTGGAATCATACGTAAGGTAATAACACTCAGAACCCTGCAGCAGTGTTCTGGAATGCTATGTAAGAGACAAACACAAAACAGAGCAGTAGTATTCTGGTATCCTATATGAGGTAAAAACACTCAGAGACAACAGAAGTGTTCTGAAATCTATGTCAGGCACAAACATTTAGAGCTCCCAGAAGTGTTCTGGAATATTATGTGAAGGACAAAAACTCAGAATCAGGTGCAGTATTCTGGAATCCTATGTGAGGGACAAACATTCAGACCCTCCTAGCAAGTGTTCTGGAATGCAATCTGTTGTAAAAACCCTCAGAACACAGAAGCAGTTGTCTGGAATCCTTTGTGATGAAGAAACTATTCCAGACCCTAGTAGCAGTGTTCTGGAATCTATGTGACGGACAAACCTTCAGAATCCAGCAATAGTGTACTGGAATCCTCTGTGAGGACATACACTCAGAACCCAGCAGTAGTGTTTTGGAATCCTTTGTGAGGACAAACCCTCAGAATCAGCAGTAGTGTTCTGGAATCCTCTGTGAGGGCCATACCCTCAGAACCAACCCGGTATTGTTCTGGAATCCTATGTCAGGAGGACAAACATTGAAACCAGCAGTTTTCTGGAATCCTATGTGAGGACAAACACTCAGAAACCAGCAGCAGTGTTCTACTGCAATCCCTATGTGAGGACAAACACTCTGGAAACCCAGCAGCAGTGTTCTAGAATCCTATGTGATGACAAACATTCAGAATTTTGTAGCAATGTTCTGCCATTCCATGTGAGTGACAAACACTCAGAAACCAGCAACAGCCTTCTAGAATCTATCGCAAGGAAAAACACTCAGAAGCCAGCAACAATGTTCTAGCATCCCTTGTGAGGGACAAACATTCAGAATCTCGTAGAAGTGCTCTGGAATCGCAAGTGAGGGAGAAACACACAGGCCCAGCAGCCCAATGTTTTGGAATCCTGTTTGAGCGACAAAGATACAGAACTCGTTGCAATGTTCTGGAATCCCATGTGAGGGACAAACACTGTGAGAATCCCAGCAGCAGTGTCTATGAGCTTATTACAGCTTACACATTTTTGTTACCCTTTTGCGCATTTTTATGTGCACACACACCAACCCACCCACCCACTTACACTATGTGAACAAACACTCAGAACCCAGCAGTGTTCTACAATCTATGTGAGGACAAACATTCAAGCTCATGTAGTGTTCTGCAATCCCTGTGTGAGGACAAACACTCAGAACCCAGCCACTGTGTTCTGGAATCTATCTGAGGACAAACATTCAGACACTTGGCAGAAGTGTTCACAGAATCCTATGAGGGTAAACACTCAGAAACAAGCAGCGGTGCTCTGGAGATGCCACAGAGGGACAAACAGAGCCCAGCAGTGTCCTGGAATCGAGGAAAATGGTGAGACCCTCGTCTCAGTTTTTACAATCCTATGTGAGGGAGAAACACTCAGAACTGGCAACAGTGTTCTAGAATCCATGTGAGAGACAAACACTGAGTTCTAGCAGCCCTGTTCTGGAATCCTATGTGAGTACAAACTCAGACACTCACGAAGCAGTGTTTGGGATCCCTATGTGAGGACCGGTCAGAACCTTGGCAGTCTTCTGATTCCCTAGAGTGGCTGTTCCGACCCTCGCTTGAGGATTCTGGAATCTATGTGAGGACAAACGCCAGAACCTACCCCTTAGTATTACAGAATCTTGAACAATACTCAAGGCGCGCAGGGTC',
  )
  expect(r1.get('cigar')).toEqual(r2.get('cigar'))
  expect(r1.get('cigar')).toBe(
    '48M4D36M1D97M5D14M1D5M1D37M2D44M1D5M1I11M2I3M2D6M2I8M1D45M3D43M1D4M2D41M1D58M1D31M2D7M1D31M5I3M1D24M2D1M1D19M1D8M1D16M2D25M1I11M1I14M2I7M1D10M2I1M1I4M1I8M1I8M1I18M2D7M1D8M1D64M2D38M1I17M2I13M1I32M2I16M1D11M1D6M1D5M3D41M1I20M1D6M1D47M1I72M4D50M1I71M1I5M3D8M1I25M1I2M1D5M1D4M1I20M1D3M2D10M1I57M1I49M1D34M1I12M2D6M1I5M1I24M1I14M2D11M1I71M1I55M1D48M1D9M2D30M1D100M1D46M1D24M1I49M2D39M3D17M1D41M1I6M1D10M3D8M1I161M2D3M1D12M1D62M1D23M1I12M5D1M2I37M2D12M1D3M1I1M2D68M1I4M1D39M1I13M1D4M2I7M2D14M2I2M1I2M1I16M1D40M1D3M1D25M1D24M1I48M1D17M2D23M2D89M1D8M1D11M2I84M1D14M2D2M2D75M1D49M1I37M1D56M1D38M1D47M1I9M2D2M1D8M1I3M2D30M1D38M1D3M1I16M1D25M1D8M1D28M4D6M1I9M1D47M1D5M3I1M1I26M1D149M1I20M2D7M1I3M1D14M1D4M2I20M2I49M1I9M1D17M3D40M1I1M2D20M1I33M1D39M4D18M2D3M1D2M1D11M2D3M1I8M1I83M1D8M1D18M3D18M1I1M2D9M1I6M1I12M2D29M1D13M3D18M3D53M1D38M2I6M3I6M2D17M1I12M1D1M1D3M2D56M3I1M1D11M2D5M2D24M1D44M2I3M1D6M2I13M1I20M3D19M1D3M3I4M2I26M1D39M1I11M1I32M2D2M1I48M1D54M1D49M1D42M1I5M1D59M2I18M1I9M1D8M1D15M1I14M1I3M1I11M1I14M3D4M1D3M1D11M4D9M1I2M1D18M1I26M1I6M2D86M1I39M1I14M3I95M2D6M2I5M2I3M1D3M1I27M1D47M1D45M3D38M1D48M2D26M1I4M1I24M1D20M1D2M2D13M1D73M2I23M1I1M2D3M1D13M1I12M4D18M2D35M1I10M1D23M2D7M1D77M1D83M1D4M1D3M1D41M1D64M1D25M1D31M1D8M2D27M1D27M1D29M1I22M3I45M1I14M2D23M2I1M3D2M1I22M1D3M1D4M2I5M1D120M2I52M1D42M1I31M2D3M1D47M1D59M1I22M1D18M1D57M2D14M1I3M2I16M1D6M1D6M2D14M2D71M1I35M4I59M1I30M3D5M1D10M2I23M1D13M1D9M2D1M1D7M2I2M1D44M1D46M3D21M2D3M3D6M1I11M1I24M2I4M1D9M2I3M1I40M1D10M2D28M2I83M2I25M2D4M1I9M1D5M2I4M1D11M1D47M1D35M3I3M1I12M1I6M1D10M1I1M3D8M3I23M2D41M2I1M4D26M1D15M4D23M2D37M1D8M1D16M1D4M2I5M3D18M1D59M1D35M1D4M1D61M2D1M2D12M1D5M1D5M1D18M3D16M1I11M5D5M2I23M1I5M3I23M1I32M3D12M1D25M1I9M1D40M1I28M2I23M1I4M1D56M2I19M1D110M2D25M2I4M1D5M3I63M2D27M1D82M1D33M1D13M1D47M1D43M1D3M1D39M3D8M1D44M1D115M3I6M1D1M1D4M1D4M1D47M1D17M1D6M2D28M2D17M1D7M1D8M1D13M1D88M2D20M8D6M80D26M1D31M1I4M1D20M1D12M1D5M3D12M1I5M1D8M1D11M1I15M1D31M1I8M1D2M1D38M1D14M1I62M3I3M1D41M1D10M1I39M1D38M1D11M1D26M3I1M1I12M2D3M1D5M1I92M1I93M3D8M5D8M4D12M39D2M1I6M1D13M1D8M1I6M2D22M3D6M1D3M2I30M1D8M1D59M1D3M2D4M1D4M3D6M3I4M1I69M2D1M1I23M1D24M1I1M2D15M1D6M1D11M1D33M1D8M1D88M2D5M1D4M1D114M1I14M1D41M2D13M2D2M1D19M2I24M1I27M1I69M1D47M1D20M5I39M1I17M1I19M1D104M1D86M1I39M1D8M1D8M1I56M1D4M1D2M1D12M1D8M1D49M1I11M1D68M1D55M1D67M3D17M1D8M1D38M1D55M3I49M1D46M1D26M4I11M1D35M1D10M1D8M1D4M1D9M3D21M1D82M1I1M2I12M1D4M2I45M1D20M1D20M2D2M1D68M1D35M1D49M1D138M1I7M5D37M1D38M1D23M2I123M1D18M2I163M1D5M1D20M1I67M1I5M1I2M2D3M1D20M1I34M3I5M1D3M2I41M1D50M1D16M2D56M1I4M1D24M1D145M1D25M1D4M1I19M5D5M2I14M1D4M1D15M1D9M1I26M1D95M1D11M1I5M1D17M1I31M3D24M1D2M2I16M2D17M3I12M2D111M1D22M3D18M1D19M1I1M2D29M1D30M1D12M3I42M1D5M1I12M1D40M1I11M1D24M2D8M1D13M2I14M1I1M1I10M1D113M1D11M1I36M1D15M1D22M1I21M1I21M1I10M1D23M3D16M1D96M1D53M1D59M1D50M1I29M2D3M18D8M1D11M2I2M8D2M3D8M1D5M2D10M1I4M1I9M1I6M1D9M1D18M2I4M1I6M1I6M3D4M1I16M1I76M1D46M1I40M1I14M1I2M1I4M1D30M2I1M1I2M1I2M1D7M1I3M1D7M1I3M3D23M1I5M1I10M1D16M3D43M1D67M3D3M1I6M1D56M1I10M2D1M1I10M1D22M2D25M1D7M2D16M1D76M2D55M1I1M2D20M1D23M1D50M1D55M1I74M1I4M1I3M1I27M1D56M1D47M1D17M1D50M1I28M2I11M2D5M3D26M1D31M3I7M1I9M1D14M2I33M1D86M1D119M1D9M2I41M1D40M2I7M1I13M1D2M1I3M4I3M73I6M3D18M3D17M1D8M1D12M2D8M1D15M1I9M1D38M1D8M1D20M1I12M1I10M2D4M1D35M1I2M1I2M2D20M3D18M6D1M1D7M1I1M2D22M1D32M1D21M1D23M1D32M1D7M2D10M2I12M1D6M1I10M4D17M2D10M1D6M3D2M1D6M2D2M1I30M1D8M1D10M1D11M46S',
  )
  expect(r1.id()).toEqual(r2.id())
})

test('pair across chrom', async () => {
  const ti = new BamFile({
    bamPath: require.resolve('./data/pair_across_chr.bam'),
  })
  await ti.getHeader()
  const ret1 = await ti.getRecordsForRange('1', 0, 272213638, {
    viewAsPairs: true,
    pairAcrossChr: true,
  })
  expect(ret1.length).toBe(2)
})

test('too few', async () => {
  const ti = new BamFile({
    bamPath: require.resolve('./data/too_few_reads_if_chunk_merging_on.bam'),
  })
  await ti.getHeader()
  const ret1 = await ti.getRecordsForRange('1', 10000, 10600)
  expect(ret1.length).toBe(34)
})
//*	0	0	TCTTCAGACCCTCGAAACAGTGTTCTGAAATCCTATGGCAGGGAACAACAGAACCCAGCCACTGTGTGCTGGAATCCTGTCTGAGGACAAACATTCAAACACTCATGAAAGTGTTCTGGAATCTTATGTGAGTGATAAGCAATCAGAAACCAGCAGCGGTGCTCTGTAATCCTTTGTGAGGACAAACAGTACACAGAGCAAGTTCTGGAGTTCTATGTGAGGGACAAACTCTCATGACAGCAGCAGTGTTCTGGAATCACTTGTGAGGGCCAAACACTCAGACTTATGCAGCAGTATTTACAGATCTTATGTGTGATGGAAAACACTCTGAACCCAGCAGCAGTGTTCTGGAATCCTATATGAGGAAAAACTCAGAACCTGCAGCAGTGTTCTGGAATCCTTAGTGAGGAGGTATTCAGAACCTCATATCAGTGTTATGGAATCGTATGTGAGGACAAACACTCTGAAACCAGCAGCAGTGTTCTGGAATCCCATGTGAGAGACAAACACGAGAATCCAGCAGCAGTATTCTGGAATCCTATGTGTGAAAACACCCAGAAACCAGCAGCGTAGTACTGGAAGGAAATCTTTGTTAGGGGCTAACATTCAGACACAAGCTGTATTCTGGAATCTATGTGAGGACAAACACTCCTATCAGTAGCAATGTTCTGCAATTCTTTAGCAGCAGACAACATCTTCAGGCCCTCATGCAGCAGTTTCAAAAATTCCACAAGAGTGAGAGATTAAACACTCCAGAACCCAGCAGAAATGCAGGGATCTATGTGAGGGCAAATACTTGGAATCCAGCAGCACTGTTCTTGAAACCTATGTGAGGGACAAGCACTCACAACAGCCACTGTGTACCAGAATCCTATTTGATTGTCAAACACTTCAGACCCTAGTAGAGGAGTGTTCTGGAATCCCTATGTGAAGGACAAACTCTAAATAACCAGCATAGCAGTGCTCTGGAATCTTTGGGAGAGAAAGCATCAGACCCTAGCAGTGTTCTGGGATCCTATGTGAGGGAAAAACATTCCAGACCCGCATAGCAGTGTTTGGAATCTATACGAGTGACAAACACTCAGAACCCACCAGCAGTGTTCTGAATCTTTTTGTGAGGTAAAAACACTCAGACCCTCAAAGCAGTGTTCTGGAATCCTGCGTGATGGAAAAACATTCAGACGTAGCTGTGTTCTGGAATCCTATGTGAGGGAGAAACATTGTGACCCTCATGTAGCATTGTTCTGGAATCCAATATGAGGGACAAACACTCAGAAGCCAGCAGCTGTATTCTGGAATGCCATATTGAGAAAAGACTCCAGAACCCAACAGCAGTGTTCTGGAGATCTATCAAGGAAATAACCCTAGAGATTGGAGCACTGTACTGGAAGTCTTATATTAGGGACACATATTCAGACACTCGTAGAAGTGTTCTGGAATACTATGTGAAAGGACAAACACTAAGAAAACAGCAGCAGGGCTTTGGAATCCTTTGTGAGGACAAAAAAACAGAACCCATCAGCAGTGTTCTGAGAATCATTGTGAGAAAAATGTTTCTAGGTCCTATTAACAGTGTTCTGGAGATCCTATGTGAGGTAAACATTCAGATCCCTCATAGCAGTGGTCTGGAATCGTATGTGAGAGACAAACCCTCACAACCCAGCAGCAGTGTTCTGCAATCCCTATGTGAGCGACGAACATTGAGAACTTCGTAGCAGTGTTCTGATATTCTATGTAGAGCAAACACTCACAACCCGGCAGCACTGCTCTGGAATCGTATGTGAGGACAACAACAGAACCCAGCAGCCGTGTTCTGGAAACCTCGTGAGGGACAAAATCTCAGAGCTCAGCAGCAGTGTTCTGCAATCCTATGTGAGTGACAAATACTCAGAACCCAGCAGCAGTGTTCTGGAATCTTTGTGAGGACAAACACTAGAACCCAGCAGCAGTGTTCTAGAGTCCTTTGTGAGGACAAACATTCAGAAACTCTCTTCCAGTGTTCTGGAATCTTAGGTGAGGGACAAACACACTGAACCCAGCAGCTGTTTTGGAATCCCATGTGAGGCAGAAACACTCAGAACTCAGCAGTGTTCTGGAATCTATGTGAGTGAAAAACACTCAGGAGCCAACAGCAGTGTTCACAGAATCTTTGTGGGCAAACCTTCAAGACCCTAGAATCAGTGTTCTGGAATCCTATGTGATGAACAAACACTCAGAACCCAACAGCAGTGTTTTTGATTCCTTTGTTTTGGAGAAACATTCAGACCATTGTAGCACTGTTCCACTATTCTATGTGAGGGACAAACTCTCAGAACCCAGTAGCAGTGCTAAGTCCTATGTGAGGACAAACACTCAGAACCCAGCAGCAGGGTTCTGGAATCCTATGTGAGGGTCAAGCACTCAGAGGCAGCAGCAGTGTTCTGGAATCCCTATGTGAGGGCTTACTAAGAACCCAGTCACTGTGTGCTGGAATCCTATGTGGGAGAAACATTAGAGACAGTCACTGTGTGCTGGAATCCTATCTCAAGGACAAACATTCAGACCATTGTAGCACTGTTCCGCTATCCCTAGCGAGGGACAAACTCTCAGAACCCAGTAGCAGTGCTCTAGGAATCCTATGTGAGGACAGAAACACTGAACCCAGCAGCAGCAGGAATACTGGAATCCTATGTGAGGTCAAACACTCAGAAGGCAGCAGCAGTATTCTGGAATACATGGCAGGAGAAACATTCAGAACCCAGTGCTGTGTGCTGGAATCCTATGTGAGGGGAGAAACACTCACAACTCAGTCACTATGTGCTGGAATCCTATCTGAGGACAAACATTCAGACATGTAGAAGTGTCCTGGAATCCTATGAGGGACAAACACTGAGAACCCAGCAGCAGAGTTCTAGAATTCTTCGTGAAGACAAACATTCAGACACTCGAAGCAGTGTCCTAGAATCTATGTGAGGACAAACACTTCTAGAACCCAGCAGAATTGTTCTGGAATCCTTTGTGATGGATGAGCATTTGAGCCCTCGTGGCAGTGTTCTGGAAACCTAAGTGAGGGCAAACACTCAGTTGTAGCAGTGTTCTGGAATCCTATGTGACTGACAAACACTCAGAACCCTGAAGCAATGTTATGAAATCCTGTGTGAGTGCAAACACTCAGAACCCACCATCAATGCTCTGCAATCCTATGTGAGGAAAGAAACACTCAGAAACCTGCAGCAGTGTTCTGGAATCTATATATGGGTCAATAATTCAGACCATCATAGCACTGTTCTGGAATGCTCTGTGAGGACAAACATTCAGAAACTTGTAGCAGAGTTCTGGAATCTATGTGAGGGAGAAACCCTCAGAACCTAGCAGTAGTGTTCTGGAATCCTTATGTGAGATAACACTCAAGACCAGCCGCAGTGTTCTGGAATGCTATGTGAGGACAAACACTCAAAACCAAGCAGCAGGATTCTGTTATCTACCATGAGACAAACACTCGAACCCAGCAGAACTGTTATGGAATCTATGTGAGGACAAACACTCACAAACAAGCAGCTTTTGGAATCCCTATGTGAGGAGAAATCTTCAGAACCTAGCAGCAGTGTTCTGGAATCGTATGTGTGGACTTCAGCACACTCAGAACCCAGCAGCATGTTGAGAATGCTATGTGAGGGAGAAACACACAAAACCCACCAGCAGTGTTCTGGTTTAATATATGCGGGACAAACACACAGAACCCAGCAGAAGTGTTCTGTAATCCCATGTGAGGGTCAAACACTCACAAACCAGCAGCAATGTTTTGGAGTCTCTTTGTGAGGGACAAACATTAAACCTCAATAAAGTGCTCTGCAATCTATCAGCGAGGAACAACACTCTACAGGCCCAGCAGCAATGTTTTCGAATCCCATGAAAGGGACAAACACTCAGAACTTCGGCAGCATTTTCTGGAATCCTATGGTGACAAACTCTCAGAACACAGCAGCGGTGTTCTAGAATCACTGTAGGAGACAAACATTCAGAATGATCATAACAGTGTTCTGGTATCTCATGTGAGGACAAACACTCGGAAACCAGCAGCAGTGCTCTGAATTCTTGCAGGACAAACAAACCGAAGAGGTTCTGGAATTACTGTAAAGGACCAAGCACTGAGAACCCAGGAGCAGCGTTCTGGAATCCCATGTGAGGGACAAACGCTCAGAACCCAACAGCAGTGTTCTGTAATCTAATTGAGGACAGACACTCACAGCCCAGCATTGTTCTAGATTCGCTGTGAGGAACCAAGCATTTCAGACCCTCGGCAGTGTTCTGGAATGTTATGTGAGGGACAACCCTCTGAACCCAGCAGGGTTCTGGAATCAGTGAGTGACAAACACTCAAAACCCAGCAGCAGTGTTCCGGAATCCTTTGTGAGGACAAGCTTTCCAAACCTCGAAGCATTGTTATGGAGTCACCTTAGCAACGAGGAACACACTCAGAATCCCGCGCGCAGCGATATGATCTTGTGATGGACAAACATCCAGACACTCTTAGCAGTGTTCTGGAACGCTATGTGATGATTGTAAACCTACAGGCCAGGCAGTGTTCTGGAATCCTCTGTGAGGACAAACACTCAGAACCCAGTAGTAGTGTTCTGGAATCTAATGCATGAGGACAAACACACTAAGAACCCAAGGAGCAGTGTTCTGCAATCTATGAGGGACAAACACTACAGCCCACCAGCATGGCAGTGTTCTAGAATCCTTTGTGAGGAAAAACATTCAGACCATCGAATCAGTGTTCTGGAATCTATATGTGGGGAGACAAACGCTCAGAACCCAGCAGCAGTTTTCTGATCCTTTTCAGACAGACAAACCTTTAGACGATCTTAGCAGTGTTCTGTTATCTATGTAAGGGACAAACACTCAGAACCCAGCAGCAGTGCTCTGGATTCCTTTGTGGGGACGAGCACTTAGAACCCAGGAGCAGTGTTCTGGAATCCTATGTGAGGACAAACACTCAGAATCCAGCAGCAGTGTTCTGGAATCTTAGAGTGAGGACAGACACTCACAACCCAGCAGCAGTGTTCTAGAATCCTTTGTGAGGGACAAACAGCATCAGACCACAGAAGCAGTGTTTCTGGAATCTATGTGAGAGCAAACACTCAGAGACACAGCATCAGTGTTTCACAGAATCCTATCTTGAGTGACAAACTAGAACCAGAACAGTATTCATCCATTGTAGAGGACAAACATTCTGTCTCAGCGAAGCATTTTTCTGGATTCCTATGCTGAGGGACACACTCAGAACCCAGCAGCAGTGTTCTGGAATCCTATGTGTGGGACAAACACTCAGAAACCAGCAGCAGTGTTCTGGAATCCTACCGTGAGGGACAAACACTCAGAACACAGCTACTCTGTACTGGGAATCTATCTGAGTATTGACAACATTCAGACTCTTGCAGAAGTGTTCTGGAATCCTATGTGATGGACAAACACTAACAAACTAGCAGCAGCGCTCTGGAATTCTTTGTGATACAGACGTGTTCAAGGAGCTCTTTAACAGTGTTCTGGAATCGTATGTGAGTACAAACACTCAAAACTCAGCAGCAGTGTTCTGGAATTCTATTTGAGGACAAACTCTCAGAACCCAGCAGCCATGCTGTGAAATGATATGTGGACAGACACTCAGAACCCAACAGCAGAGTTCTGGTATCTAAGTGAGGAACAAACACTCAGAACCCTGCAGAAGTATTCTGGAATCATGTGAGGGACAAACACTCAAAATCCAAGAAGGCAGTGTTCTGGAATCCTATGTGAGGACAAACACTCACACCCTCGAAGTGTTCTGGAATCTATGTGAAGGACAAACACTCAGAACCCAGTAGCAGTGTTCTGGAATCTGGTGTGAAGGACAAGCGTTCAGACTTGCTCGTAGCAGTGATATGGAGTTGCTGTAGAGACAAGCATTCCAGACACACTTATGTTCTGGAATCCTAAGTGAGAGAAACCCTCAAAAACAAGCTGCAGTGTTCTAGGAAATCTATGAAAGGACAATCCCTCAGTATCGAGGCAGTGTTTGGAATCCTATCTGAGGGACAAACACTCAGAACTCAGCAGCAGTGTTCTGGAATCCTGTGTGAAGGAGAAACACTAGAACCCAACAGCAGTGTTCTGATTCCCGAAGTGTGGGACAATCACTCAAAACCCAGCCACTGTGTTCTGGAATCCTATCTGAGGTCAATGTAGGAACCTCGAGGAAGAGTTCTGGAATCCTATGTGAGGGAAAACACTCTGAAACCAGCAGAAGTGTTCTGGAATCCTTTGTGAGGGACAAACACTGAGAAATCAGAGCCGTGTTCTGGCATCCTATGTAGCGACAAACACTCTGAACCCAGCAGCAGTGTTTTGAATCACGTGAGCGACAAACACTCAGAACCCAAAGCAGTGTTCTGGAATACTTTTTGAGGACAATCATTCAGAACCTTGTAGCTGTGTTTCTGGAATCATATGTGAGGGCCAGCGAACACTTTGAACCCAGCTGCAGTGTTTTTGATTCCCCTGTGAAGGGAAAAACACTCAGGGCAGCAGCAGTGTTCTAGAATCAGCGTAATGGGACTAACATTCAGACCCTCAACGGTAACTTTTGGTCTATGTGAGGGACAAACACTGAGAACCCAACTGCAGTATTCTGCAATCCTTTGTGACAGAGAAACACTCAGACCATCGTAGCAGTGTTCTGGCATCCTATGTGCAGGAAAAACACTCCAAGAAACCAGCATCAGTGCTCTGGATTCCTTTGTGAGGGACAAACAAACAGAACCAGCAGCAGAGTTCTGGAATCCTATGTTGAGGACAAACACTCCAGAACCCATCAGCAGTGGTCAGAAATAATTTGAGGACAAACATTCAGAACCTAGTAGCAGTGTTCTGGAATAGTATGTGAGGACAAACACTCTAGGCAAACTGGCAGTCTTTTGGAATCACACGTGAGGGACAAAAACTCCAGAACCAAGCAGCAATGTTCTGAATACCATGTGAGAGACAACACTCAGAGCCCAGCAGCAGTGTTCTGGAATCTTATTTGAGTGACAAACACTGAGCTTAGCAGCAGAGTATTTACAGAGTCCTTTATGAGAACAAACTTCAGACACGCAGTCTTAAGATCCTATGTGAGAGACAAACCCTCAGAACCTTGAAGCAATGTTCTGCAATCCTTTTTGTTGGACAAACATTCCAGACCCTCGTAGCAGTGTTCCAGAATCCTATGTGGCGAAGGAACAAACACTCAGAACCCAGCAGTAGTGTTCGGGAATCCTATGGGAGGGACAACCATTTCCAGATCCAGCAGCAGTGTTGTGTAGTCTGTGAGGACAAACACTTTCAGAACCCAGCAGCTGTGTTCTGAAACCTATGTGAGGAAAATCATGAACCCAGCGTGTTGTGTTCTGGAATCCTATCTGAGGGAGAAATATTCAAACACTGTAGAAGAGTTCTGGAATCCTATGTGAGGGAAAAACCCTCAGAAGCCAGCAGTGCTCTGGAATCCTTTGAGCAAACAAATCAGAACCCTAGAAGCAGTGTTCTTGGATCTTTCCAGCTAGGAAAAACAGCTTCAAGACCCTCATAATAGTATTTTGGAATCCTATCTGAGGGACAACACTCAGACCAGCAGCTGTGTTCTGGAATCCTATATTATTAAGATAAACACTTAGAACCCAGCACAATATTCTGGAATACTACGTGAGCGACAAACTTTCAGAAGTTTGTAGCAGTATTCTACAGAATTCTATGTGAGGGACAAACACACAAGGCCAACAACTTGATAAGTGGTTCCTAAGTGAGGACAAACATTCAGAACCCAGCAGCAGTGTTCTGGTATCCTATGTGAGGACAAACACTCAGAACCCAGCAGCAGTGTTCTACAGAAATCCCTTTGTGAAGAGAAAAATGGCAGACCCTGCGCAGTGTTCTACTGGAATCCTATGTGATAGAAAAGTTCATACCCTCATAGCAGTGTTCTGGGATCCTATATGAGGTTGGCTTACAGAACCCACCAGCAGCGCTCGGAAACCACACTCTCTAGTGTTCTTGAATCCCATGTGAGAGAAACCTTCATACCCTCGTAGCATTGTTCTGGAATCAATATGAGGACAAACACTCAGAACCAGCCCAACATTCTGGAACCTTTATTGAGGATAAACATTCAGACCGTCATAGCAGTGTGCTGGAATCCTATGTGAGGGACAAATGCTCGAACCCAGCAGCAGTGGACTGGAGTCCTATGTGAGGACAGTACTCTGAGCTTAGCAGCAGTGTTCTGGAATCCTCTGTGAGGGACAAACTTTCACAACTGGCAGTGTTCTGGAGGCTTGTGAGTACAAACATTCAGAACCCAGCAGTGTTCTGGAAGTCCTTTGTGAGAACATTGTTGGAACCTCATAGCAATGTTCAGGGAGTAGGCGTACGTAAGGGACAAACACTCAGGAACACAGCAGCAGTGTTCTGCAATCCCATATGGACAAACACTCGAACCCAGCTGCAATGTTCTGTAATCCCTGTTTGACGACAAAGGCTCAGAAACCAGCAGCACTGTTCAAGAATCCTTTTTTGTGTGACAAACATTCTGAACCTCTAAAAGCAGTGTTCTGGAATCCTACTGTGAGGACAAACACCACAATCCCTGCAGCAGTTTTCTGGAATCCTTTGTGATGGACAAACATATTCAGACCCTCGTAGCAGTTTTCAGAATCCTATGTGTGGGACAAACACTCAGAACACAGCAACAGTGGTCTAGAATCCTTTGTGTGGGACAAAGATTCAGAACCCAGCAGCAGTGTTCTGGAATCCTATCAGGTACAAACACTCAGAAACAGTACAGCTTGTACTTTTGGATTCCACTGTGTACTGGAATCCTATCTGAAGGAAAAACATTCCGAACTTCGTAGAAGTTTTGGAATCCTGTGTGACGGACAAACACTAGAAATCTGCAGCAGTGTTCTAGAATCCTTTCTGAGTGACAAACAAACAGAACCCAGGAGCAGTGTGCTGCTATCCTTTTGAGGAAAAACTTTCACATCCTTATAGCAGTGTTCTGAAACCTATGTGAGGAAAGAAATTCAGACCCTCGTAGCAGTGCTCTGGAATCCTATATGAGGACAAACACTCAGAACCCAGCAGCAGTCTTCTGGAATCCTTTGGAGGAAAAACATTCACACCCTCGTAAAAGTGTTCTGGAATCTGTGAAGGAAAACATTCAGACCCTCGTAGCATTGTTCTGGAATCTAATATGAGGACAAACAGTCAGAACCCAGTTGCAGTGTTCTGGAATACTATGTGAGTGACAACACTCAGAACCCAGGAACTGGGTTCTGGAATTGTCTGTGCGGGCCAGTCATTCAGAACCTCATTATGATATTTCTGAGTCTATGTGAGGGAAAAACACTGTGATCTCAGCAGCAGTGTTCTGGAATCTATGTGAGGGCGAAACCTCTGACCAGCAGTCGTGTTCTGGAATCCCATGTGAGACAAACACTGAGATCTAGCAGCCTGTTCTGAATCCTATGTGAGTACAAACTCTCAGAACCCAGCAGCAGTGTTATGGAGTCCTTTGTGAGAGACAAACATTCAGACCCTCGTAGCAGTGTTCTGGAATCTTGTGAGGCACAAACACTCACAGCAGTAGACCCTCGTAGGAGTGTTCTGGAATCTACGTAAGGGACAAACACTCAGAACTCAGTGATTATTTTCTTGAAAGCTAAGTGAGTACAAACACTCGAAACCAGCAGTGTTCTGGGAATCTTGGTGAGGACTAACACTCCAGAACCCAACAGCATGTTCTGGGAGTATATGTGAAACAAGAACTCAAGAACTCAAACAGTGTTCTGGAATCGTATGTGAGGAACAAGCAATCAGGGCCAGCAGCAGCAGCCATGGAATCCTATGTGAGGGACAAACACTCAAACCCAGCCACTGTGTTCTGGAAACCTATCTAGTGATGACAAACATTCAGACACTCGTGGAAGTGTTCTGGAATCCTCGTGAGAGGCGGCTCAGAAACCAGCATAGGTGTTCTGGAATCCTTTTTGTGGAGAAACAAACAGAACCCAGCAGCAGTCTTCTGGAATCTATGTGAGGGAAAATATTTAGAACCCCGTAGCAGTGAAATACCTGGAATTCTATGAGGACACAACACACAGGACCCAGCAGCAGTGTTCTGGAACCTTATGTGATGGACAAACACTGAGAACACAACAGCAGTGTTCTGAAATCACATGTCAGCAGAAAAACATTCAGAAATTCATAGCAGTGTTCTGGAATCCTTTGTGACAGACAACACTCAGACTGTCGTAGCAGTGTTCTGATTTCCCATGAGAACAAACACAGCTAACATGTCTCAAAATCTCATGGGATCTATGCAAGGAACAACACAAGAGCACCCACACTATGTTCTTAAATACTAAAGAAACAACTTATTCAAACACTGGCCAAAGTATTCTAGAATCTATGTGAGGATAAACACTCAGAAACCAGCAGCAGTATTCTGGAATCCTTTGTGAGGGAAAAACATTAGACTCACGCATTCTTTAAAAATCTCTGTGTGAGGGACAAACCGTCTGAACTGAGCAGCAGTGTTCTGCAATCACTCTTGAGAGACAAACACTCACAGACAGCAGCAGTGTTCTGAAATCTAAATGAGGAACAAACCCTCAGAGACAGCAGCAGTGTTCTGAGTCCTTGTGGGGTACAACATTCAGAACCTCGAAGCAGTGTTCTGGAATCTATTTGAGGACAAACTCACAGAACCCAGCAGCAGTATTCTGGAATCCCAAGTGAGGGACAAACACTCAGAAACCAGCAGCAGTGTGCTGGAATGCTTTGAGGACAACATTCAGACCTTCGAAGCAGTGTTCTGCAATCCTATGTGATTGACAACTCTCAGAACCTAGGAGCAATCTTCTGTAATCTGTTGTGATGGAGAAACATTCGGAACCTCTTCGCCAGTGTTCTGGAATCTAGGTGTGGGAGAAACACTCAGAATCCAGCAGCAATGTTGGAAGTCTCTGTGAGAAAACACTCAAGGCTCAGCAGCGTAGTGTTCTGGAATCCTATGTGACCAGACAAACACTCAGATCACTGCAGCAGGGGGTCTGAAATCCTATGTGAAGGATAAGCACTCAGAACCCAGGAGCAGCGTTCTGGAATCCTTTCTGAGGACAAACATTCAGAACCTCGTAACAGTGTTCTGGAATCTTATGTGAGGACAAACACTCAGAACCCAACTTGGCAGCATTGTTCTGGAATCTTAGATGTGGGACAAACACTCCAGAACCAGGCATTAACAGTTCTGGAGTCCCATGTGAGGACAAACACTCAGAACCCAACAGCAGTATTCTGGAATCCTATGTGAGTGACAAACACTCAGAATCCAGCAGCAGTGTTCTAGAATTCTTTGTGTGGGACAAGCTTCATGCCCTCAAAGCAGTACTCTGGAATCCTATGTGAGGGAGGAACAGTCACAACCCAGCAGCAGTGTTCAGGAATCCTTTGTGACTGGACAAACATTCAGACCGTCGGAGCAGTGTTCTGGAATCTAAGTGAGGACAAACTACTCAGAACCAAGCCACTGTGTTCTGGAATCCTTCTGAGGGACAAATATTCAGACACCGTGAGTGTTCTGGAATCTATGTGAGGACAAACACTCAGAAAACAGCAGCAGTGCTATGGAGACCTTTGTGAGGAGCAGCAAACACAGCCAGAGTTTTATTCTGTAACCTTTTTGAGAGAAAACATTCAGAACCCCGTAGCAGTGTTCTGGAATCTATGTAGGGGACAAACATTCAGAACCCAGCAGCCGTGTTTTGGAATCCTGAGTGAAGACAAAGATTCAGAACTTCATAGCACTGTTCTGGAATCCCAGCTGAGACAGAAACACTCAGAACCCAGCAGTGTTCTAGAATCTATGTGAAGACAAACCCTCAGAACCCAACAGCAGTGTTCTGGAATCCATGTGAGGGACAAACACTCAGTACCCAACCACTGTGTTCTGGAATCCTATATGAAAAGGGACAAACATTCAGACAATCGTAGAAGTGTTCTGGAATCCTATATGAGGACAACACTCAGAAACCACCAGCAGTGCTCTGGAATCTTTTGTGAGGACAAAAATCTGAACCCAGCAGCACTCATTATTCTCTAATCATTTTAGGGACAAACGTTCAGAACCTCGTAGGAGGTTCTTGAATCTAAGTGAGGATAAAGCCCAGGCAGCAGCAGTGTTCTGGAATCTGCGTGAGTGACAAACACTCCGAACCCCGCAGGAATGTTCTTGAATCCTTTGTGAGGGACAAACATTCAAACCCTCGAAGCTATGGTGCTATGGAATCTATACATGAGGTACAAACAGTCATAACCCAGCAGAAATCTTCTGGAATCCTTGTTATGGACAAACATTGAGCCCTTGTAGCAGTGTTACGATCTAATGGAGGCACAAACACTCAGAACCCAGCAGCAGTGTTCTGGAATCTTATGTGAGGGACAAACACTGCAATCCAGCAGAAGTGTTCTGGAATCCTATCTGAGGACATACACTCAGAACCCAGTAGCAGTATTCTGGAATTCTATGTGATGGTACACGCTCAGAAACCAACAGCTGTTTTCTGGAATCTTGTCCAGTGACAAATATTCAGACACTCGTGGAAGTGTTCTGGAATCCTATGTGAGGGATAAACACTCAGAAACTAGCAGCGGTGATCTGGAATCCTTTGTAGAGGCTCAACAGAACCCAGCAGCTGTGTTCTGGAATCTTTGTGAGGAAAAATATTTAGACCCTTGTAGCAGTGTTCTGGAATCTATGTGAGGGACAAACACTGATACAACCCAGCGGCAGTGTTCTGGACTCCTCTATGAAGTCAAACCCTCAGAACCCAGCAGCAGTTTTCTGAAATAAAATGTGAGCAACAAACATTCAGAATTTCGTAGCAGAGTTCTGGAATCCTAGCGAGTGACAAACACTCAGGGAAACCAGCAGCAGTGTTCTAGAATCCTTTCTGTGGGACAAACTTTCAGACGCTCAAAGCAGTGTTCTGGAATCCTATGTGATGGACAAACACTCCGATCCCATCAGCAATGTTCTGCAATCCTTTGTGATGGGCAAACATTCAGACCCTCGTAACAGATTTTGGAATCTAAGTGAGGGACAAACACTCCAGAACCCAGCAGCAAGCAGTGTTCTAGAATCCTATATGAAGAACAAACACTCACAACCCAGCAGCCAGTATTGCTAATCTGTTTGAGGGACAAACACTCCAGAACCCACTCACTGTGTACAGGAATCCTATCTACCATGGGCTAACACATTCAGACCCTCGTAGCAGTGTTCTGGAATCCTATGTGAGGAGAAACTCTAAAAAACCAACAGCAGTGCTCTGGAATCCTTTATGAGGGAAAACATTCAGACCTTTAGCAGTGTTCTGGAATCCTATGTGAGGGAAATATTTTCAGAGCCTCATAGCAATGTTTCTTAATCATATATGAGTGACAAACGCCAGAAACCAGCAGCAGTGTTCTGGAATCCCTTGAGAGGGAAAAACATTTACACCTTCATAACAGTGTTCTGGAATCCTTACTGTGGGAAAAATATTCAGACCCTCGTAACAGTGTTCTGGAATCCTATATGAGGGACAAACACTCAAAACCAGCAGCAGTGTTCTGGAATCTATAGCCAGAGAAGCGTACTCAGAGCTGTACAGTGTTCTGGAGTCTATGGAGTGACAAACTTTTGAAATTCGCTGGCAGTATTCTGGAATCTTATGTGAGGACAAACACACAGAACCCAGTAGCAGTGTTCTGGAATCTTATGTGAGTAACAAACACTCAGAATCCAGCAACAGTGTTCTGGAATCCTATGTGAGGACAAACACTCCAGAACTAGCAGCAGTGTTCTAGGAATACTTTGTGAGGAAAAACACTCAGAACACAGTAGTGTTCTGGTATCCACTATTATTATAGAATCCTATCTGAGACAAACATTCAGAACCTAATAGTAGAAATGTTGCAATTCTACGTGAGGGACAAATACTAAGAAATCTGCAGCAGTGCTCTGGAATCTATTGTGAAGGTCAAACAAATAGAACCCAGTAGCCTTGTTCTACAATACTTTATGAGGAAAAACTTTCAGACCCTCATGGTGGTCTGGAATCACACGTAGGAACAAACACTCAGAGACAGCAGCAGTGTTCTGTACTCCTTTGTGAGGACAACATTCAGTTCCTCAGAGCAGTATTTGGAATCCTATGCTTTGAATGACAAGCACTAAGAAACCATCAACAGTGTTCTGGAATCTATGCTGAATGACAAACCTAAGAAACCATCAGCAGTGTTCTGGAATCCTTTGTGAGTAGCTAAACATTCGACCCCCTTAGCAGGGTTCTGGAACTATGTGAGGACATTCAGACACTTAGCAGTGTTTTGGCGCCTTAGCAGTGTTTGGAAACCAATGTGAGGGCCAAACAGTCAGAACCCAGCATCAGTGTTCTGGAATACTTGGTAAGGGACAAGCATTCAGAAAATCTTATCAGTTTTCTGGAATCCCAACTGAGGAGAAACGCTCCAGAAAATATCTGCAGTGTTCTAGAATTCTATGTGAGGACAAACCCTCATTGCGAGCTGCAGTGTTCTGGATTCCCTAGGTGAGGGACAAACACTCCAGAACAAAGCAGCAGTGTTCACAGTCTCATAACGATGGACAAAAACTCAGAACCCAGCAGTGTTCTGATACCTATGGGAGGGACAAACACTCAGAACCCAGCCCCTGTGTTCTGGAATCCTATCTGAAGGACAAACATTCGGAGACTTGAAGAAGTTTTCTGGAATCTATGTGAAGGACAAACAGTCAGAAACCTGTAGCAATGTTCTGGAATCATTTGCAGGAACAAACACTCAAAACTCAAAAGCAGTATCCTGGAATCCTACGTGAGGCCCAAGCCTAAGAACCCAGCAGCAGTATTTTCGAATCCTTAATGAGTGACAAACAGTCCAGAAACTTGCAACATTATTTTAGGTTGCTGTCTCTAGTACAGAGTTCTGGCCAAGAACAAACGCCAGAACAACCACTGTATTTCACAGAATATTGCTCTGAGAAAAAATAGCCGAGCCTCGTAGAAATTATTTCACAGAATCCCTATGGTAACCAAATACTCGAAAACCGCTCAACAGTGCTCTGGAATCCTTTGTGATGGATAAATAAACAGAGCCCAGCAGCAGTGTTCTGGAATCCTTCGTGAGGACAAACATTCAGAACCTTGTAGCCGTGTTCTGGAATCGTATGTGAAGGGTCAAACACTTTGAACCAGCAGCTGTGTTCTGGAATCTCTATGTGAGGGACAGAAGCACTAGAACCCAGCAACAGTGTTCTGTAATCCTTACTAGTAGAGGACAAAGCACAAGAGCCTTAGCATTGTTCTGCAATCCTTTGTGTGGGGACAAAACACTCAGGCCCAGCAGCAGAGTTGAATCCCATGTGAGGGACAAACGTTCAGGCACTCAGAATAGTGTTTGGAATCCTATGTTAGGGACAAACACTCAGAAAACTGCAGCAGTGTTCTGGAATCACACGTGGGGATGTGACTGAATCCTGATAGCACTGTTGTGGAATGCTCTGTGAGGAACAAACAATCAGACCCTCATCAGCAGTGTTCACAATCCTATGTAAGTACAAACCCTCACAACTCAACTAACTTTCTGGAATTCTATGCGAGGACAAACTCAGAACCTAACAACTTGTTCTGGAATCATACGTAAGGTAATAACACTCAGAACCCTGCAGCAGTGTTCTGGAATGCTATGTAAGAGACAAACACAAAACAGAGCAGTAGTATTCTGGTATCCTATATGAGGTAAAAACACTCAGAGACAACAGAAGTGTTCTGAAATCTATGTCAGGCACAAACATTTAGAGCTCCCAGAAGTGTTCTGGAATATTATGTGAAGGACAAAAACTCAGAATCAGGTGCAGTATTCTGGAATCCTATGTGAGGGACAAACATTCAGACCCTCCTAGCAAGTGTTCTGGAATGCAATCTGTTGTAAAAACCCTCAGAACACAGAAGCAGTTGTCTGGAATCCTTTGTGATGAAGAAACTATTCCAGACCCTAGTAGCAGTGTTCTGGAATCTATGTGACGGACAAACCTTCAGAATCCAGCAATAGTGTACTGGAATCCTCTGTGAGGACATACACTCAGAACCCAGCAGTAGTGTTTTGGAATCCTTTGTGAGGACAAACCCTCAGAATCAGCAGTAGTGTTCTGGAATCCTCTGTGAGGGCCATACCCTCAGAACCAACCCGGTATTGTTCTGGAATCCTATGTCAGGAGGACAAACATTGAAACCAGCAGTTTTCTGGAATCCTATGTGAGGACAAACACTCAGAAACCAGCAGCAGTGTTCTACTGCAATCCCTATGTGAGGACAAACACTCTGGAAACCCAGCAGCAGTGTTCTAGAATCCTATGTGATGACAAACATTCAGAATTTTGTAGCAATGTTCTGCCATTCCATGTGAGTGACAAACACTCAGAAACCAGCAACAGCCTTCTAGAATCTATCGCAAGGAAAAACACTCAGAAGCCAGCAACAATGTTCTAGCATCCCTTGTGAGGGACAAACATTCAGAATCTCGTAGAAGTGCTCTGGAATCGCAAGTGAGGGAGAAACACACAGGCCCAGCAGCCCAATGTTTTGGAATCCTGTTTGAGCGACAAAGATACAGAACTCGTTGCAATGTTCTGGAATCCCATGTGAGGGACAAACACTGTGAGAATCCCAGCAGCAGTGTCTATGAGCTTATTACAGCTTACACATTTTTGTTACCCTTTTGCGCATTTTTATGTGCACACACACCAACCCACCCACCCACTTACACTATGTGAACAAACACTCAGAACCCAGCAGTGTTCTACAATCTATGTGAGGACAAACATTCAAGCTCATGTAGTGTTCTGCAATCCCTGTGTGAGGACAAACACTCAGAACCCAGCCACTGTGTTCTGGAATCTATCTGAGGACAAACATTCAGACACTTGGCAGAAGTGTTCACAGAATCCTATGAGGGTAAACACTCAGAAACAAGCAGCGGTGCTCTGGAGATGCCACAGAGGGACAAACAGAGCCCAGCAGTGTCCTGGAATCGAGGAAAATGGTGAGACCCTCGTCTCAGTTTTTACAATCCTATGTGAGGGAGAAACACTCAGAACTGGCAACAGTGTTCTAGAATCCATGTGAGAGACAAACACTGAGTTCTAGCAGCCCTGTTCTGGAATCCTATGTGAGTACAAACTCAGACACTCACGAAGCAGTGTTTGGGATCCCTATGTGAGGACCGGTCAGAACCTTGGCAGTCTTCTGATTCCCTAGAGTGGCTGTTCCGACCCTCGCTTGAGGATTCTGGAATCTATGTGAGGACAAACGCCAGAACCTACCCCTTAGTATTACAGAATCTTGAACAATACTCAAGGCGCGCAGGGTC	MS(C92>\7r3[95d{H7LOH{gY>FxkE.?%FA33`T<A]oo\LGA35GQjN>{@{AHLF0@65HO7.<'{)6M3PJ?E0=<2GBJCP{;6EZKC'{@\3"B8.%$.*%64`sl9K{H{4CBN[MM6EC2VEMy;%{N>B{t@6ip{:DZ7?6<L9&B40;T1Q7d-ITTK4KZ3${[BPL<8;,*"+:.168(-"H@@E>#_WP%s(3;`>M:_Fbih:lCJBc{<3Op?Tk>a675../GM=b5umAmF*;2A:f.(-IIVkg4O9+FHZ4,1"("1$-$&'"+'""#%"'#4DH;""*(%7"")11"+",B-4(?3@C-(0"79F`a6,{?{i;;lD8C:dye2EytVBI*=C8F"#@30`"3PP.769{\{D/tP:WQPXAT:w>T1T(65/H0G(ESeB>227"*/"@Wi5venZ']NG@C<fE7V-dlg8m$d(Z?<<EcB<[J4-KETd{;R50JVKxl{FK@{BX7OC<GG{sJ{E&A{P>{oS1b.:>@*:V=r*_82251T2SA6{c3PEIK<90:7[M:/R_*6@N:Q9L9,5B6SId299'V4,7>KG,C=@7-24,=*0G6".$A.0)%"($>"""-OFD5,10+*F=FF/{P3*"%)"*"3""@))"78")%:/*.)2028H{{8ZA<BZ>U2#DCB(-3?/K@SVCR{[7kUiF903>6V0GY;""""#)'02**'0091A/(.1(*454($.""&""%))H8-)2*-%%=%@%&":#"0.0("&,("+*?=65"D@O3`i5$6'0+-K3NV/93/"?d)+/E7>J=BC@AoFF9gD6"""",C"44QM:*@77?9,L{3Om5R_GB68JCNA3)(80Q>J[Fo#Q0$O;COW0)c5ZQ:&/`=B8S.CDBR7Br=EJ.W=<"")&?<$V60#"()13T?K_2BiEB-P2+05Y7a]Z3#%*"8G7Y>?U@DLiah>-8CC{<-c><&m{>{C`B9&1O5K=G075"%5A3<T"ED<"@=%TJ5,.")*%")$1'?F),ZMIng9?M@po]2:Ck\4JU7N2R72d7"75*OabL2VJY"IFqG@tA1zBD'Z;2f3\ed0"9414HOK:26YP@k.TCU{AD3&CE6gf`Qy8Y5I<^=6IDjjtG,--1Bu6{{{QAW{F1Gi"{{{UC0'A@5zE%{?YFI{ZS:4^N3WT6ArpjH3?WX264V{{9{i"RqpJ?.e8)1UG0"-q:9IA6w{FxD{k<;=sNDQ=>Di^5{4>;'?0>,B@'"#"&(.4,@,"%""+23:1AO1R'{?H6fDW{J0JqNCd\?Pw{=P6#<L5DHG,16i:IC34V/Ojo]5B.OT>I1.9+0""0;/,#K{ec?3v1^3^{`F{Y.5@2WD5G={<M)%(.(()>D4'=*'-0%00(*"##OXFHJ%J)'F(R@0C>1Q03H*:a^%5"TTjNZD{pSphUZRCF6:KNsd10WE5.+T?3@_S"d@=`uS?.5(%<FI3CB868?83%]R@9o{<H<5q%E9=D{@I{fK:sA1{QE7#hm%>a=H-Baj:FU{SYSA4;{{ypt4B{jgI&WFJR7fX;<EK3oi<;'(#''3"""61<qc:;gVD)""(*,,$%+(1-51("&A<J2P=\lX9FS?-)&>OG>3F+My]AIK3ND=7"E1'.".>fYS>$IrSP=F<{OPc<6?>1DG5?pH@@go7d{In={:3hS]:<aM?G{CmPN.A<=R;sh\5PE<7pQs{@LBG.CQ&'2fS=%%72Aaa{D=jA"0T@N=pFW8K@{KWVDo4:)$>51$%""+(@QA2kR2<(IHB?G@'w5"+1-M7>"=.&PVa%{59J@9=5]-TL/KPH{':D6+).MDAHz5v5/&8"C=C=J\>HW4"08)GA71EzT9{EI7pt\:9{97d5"(&P9E=@7MJ2QO2{wDZ6JR{x?Q@PC;=UEHM{EgFy\<)"F;6_FD%I.2+:2]A;;={{PLW,{DiK;K{@6Coa(D,ARxFFC2Dwdz@)c6L<C2JKYDN5wM4]w{^7D8@6=J3W[T49FpA{:@-yW<E>VS2(A-c6iO'HB?n2fh9I%x4X;\lUr{g>a/>xOR\Q{=?=?92iwwQWr=d.2.2%+(%IB54nACF&{i7G/M{C/C:m.XoC??5H7/>22&J5/:C2E9zdY{;NoM3H470*98??OHxr{xsD-*$FDAR'9%-F%)0e1;iFW2ba3#".'(%?.+3G29.X;=Xk%"/"9""6Q@d{@F{r$K6/;53@>B*F&@;9EYhA2c=Zi.KbdC;,@2>0%#2p<y97m,m%S4UNGG_9{{tv{{{ANGOTwKunx{l%G5Y%fQB.tU6CsP[G5{Z8NxY:5'E5qn"C@%h8jx<E8m>E{b:{DK^Da8-i1OD{s{F3m0\QNdSC6UH4.5%(&5ZRFJCEP{s@_BjF{J>7&L9{v_S_{^1bA2_7t\K\0aRHZc;@7_LCC^2@{7G0'0%$@"B5"@;:cC#):8GCA_9{ZC{[t1Ax{7>BRt1F:b4F{s6M,)*+*"%*24IB3mY2CHD="=Q?3=.*F+{8CA1DTP@/V'{HU?)m=Z(?>"+-"9JYn8<`#L5;8Z8)M:p;]2[G<6G8U=A7DS>IP{EM,eLAHcH'HN{\GU{n3.#\7qCHD:'C2w5_9FF&13-0Ii8\ZwBA-5>>{R{:3z7{uW{WY;S8B*LhFse"[*HS=E5ODB{49R:0:'mLE72"27:>Rh?909,*("-+&:A+,"$"6%["I6r?@62-20'8F?8_{=8M(C@GSSDWFN4I[5T^5`CLO`Hq'X$7>2=<6(.),/B85)F,7/kXH2k{MV{a5D8("B3=D</,Y${/0FwoIGA4;bD;{{T2;&D6A8"E1;=C>%GE<D?4<4BB=0:0(*3a#;F`=OBBL`{LAPONEjE;YZY<JVV7A1"/A3"0A^0U'AW'l"@CBPD9K,M9sd?mE{\8<&YgDKCB<Y1^0/e2A:G`0;_6>{G9H%A`OL3,CQQGJKM5ka3CwIU3n_A1"=/"6-0<ZU\9>@R5{Ea9CA9g0R@{28?55Zp6Q1"'=("BMNU(Q0n7De*a2&J\ml0K{{5@D#3)0/-*.#%4$*""%'A)UK1/%="E>I?<A{R=AYZ3yt@HwID]2+F\2{Me{tC{;APUD:<&>*.""'""6:=GAe:dT5L{{3?@Xw9:F(.>)+>p[:2i359/LQ5ZQEXlCD_l/1PKjI2OEBQ{yko?beM-<)C8-*CJ8\n3G0"A?AJIs#w;A1LBYSG{^3&J4;JV=u4/U:9I.45-L3;]90jx7G:":A>F_k3-ZM5VBML2H\{Ff;G9>)<E76bF,7()EA::NE{5]T_Z4{rG)KMD<kf{Q57(W6raGAn{.?G9(s9O>UAA?A/FFwDC/{x3pRKT6*COPSWy4l{84,G,T&rd4:W9R@;BM.7ew;>(<(&h1g;{UFA9GQne50AEK;>{ghMi#t17<3[&`-W>B7(,'2"""""2$$:%$($%""&.2^GCj`Z_H){>>/A1G7A;+G-:S5%&Q[<4"N=WdP3"-7]L5yN:c./$-b:@UfM6V6*$(&B:gHb]<u{T<'"=0j5l&{5{OP{U{Y:S2{S>Bsd";GB6GI7AY?6,2d)m<;,*M?A<\f4HCU"'*("7;86"a/-Caf1Jr43D{w8>B31P0;:<PA?m{e?wA{\A6=9?VG0>'HC+{<@DA,BAG>,09LP3"#(",2,.-*"D;--+2%D'40=v"?Q=.$EjnA$-@>3Ru<;@oZ:z]E62dEk1FJ:P{{5<{_4*JSXPAJ@18G0B8EJuk0S4=7-<.%#?H<RNo:94<K<{_cB(T/%""d&Y)===.3B;<@*{`6{f9Q5KS017)/%%JDL8#9C>\r{;ZX6G:HESe{_2w{zW+<'4-#=6cpQ*#cQA{ODLOe5@"")$/'&/F/&&,0:<:z+%DkVJNH{nD>*4""""+"*>073)E*F%E.:#"+30$(#$F<7":A{Ktv{zK;{v-2r{:CHVV{40:>%",`/M0/E1=1S>+2]G)S.lU@*{{{Y2;U@83?[QHD1%3M;,/Iv<-N<\:{*vJKO:{RA7ET2T7\wdMlxt?<C=,%Db=*?EL6w=BtL@)jG'/*#**/,8;>E)@1"&<3wm4DpH7@e4J3*8%)[0;_G>b{YUJ2IO">"/FBJCQ@=QEtGR5&eK6>&""4%"'"""323YK{GGQa--@33I7'7g4CC;+I-(")"""#,58&+4,"/"3+D5"\{{7{E,{8{{{xj3uNGJDJ4T4{)5C2dB-1(EW=^{YF7[x8X0$]D8P)20sK'5:EET6bFqLg11+.-:4;6"&%2L6HNI?8F9OC2?596K.&D#=CN-{d1nXS={x{$\G/&D1$,1/("""-18"4;\kM=<{H>nU8"$+<0M6u`T,08{@<MDg]BE=SJ84qc<<G4'd{7{>qT<9g67517T\W*]UHB=$%("9(:E97ej_FX{F:-"L:-z{MGs9tAE>S`2EArvZ$B";%:;f9*@L>=2/0OB;9H+(0=4'@?U7GYBD0@/1.9aP(#0%(#5#'6$##'"+#""""%005W=IL296(7"02",2cG,00'""""+&#"+"##"=)*54>qp5W\5t,{CO4B/I+/OB.*I7NR{t<5aA6v`<T,gv4<0%F0K"(**,3""%"%",##=7,*"&%"3-,,+9$;<#RU@{{74DA=FEA1VjG4]?mU{HH4"H:2]{LO{Y1LJ>G6a;^1i^:AZNyTK9E+zF2$"4zm9`<MY{B69:6(SN650*"("$)-C+(G.F:hiX4PFW_{iT@82{YK{AFYK{GA5"9#""""#+$""$7.6BNN?3t={ao6W{k{I9R>cz[1H{8@S,ikuG@-tV<3k<.m2@34=63>BMJ{AZcR{{&BAaA@2"%1<U\nm=#>N>f9+3(@>4`^FK{?{Xg3K]<?RqbD/&-".2<=M?1%+//7pmoFRk=BUr{QmpfE7=A>Ig{Ff6KDk{vMN0MJDb818,5>*22[V.5UJ.'H#E@;d?A&X8e>G5_.w]F;(F8Z#{,&N:J_fa3B,x{FH3n<G?d%,I5lIC0o?9{{og393J5Qj5J{{7RC)AZ6b5KtZ5Q2/"<6F8'ZB{lwE?{G{UB7m86H7{ve3;{{R4C@(@%#"G<kWBIKM4gRM8%^>;_LA:z?uFB:e>5Z=4{O1{3eyBD&Beu\0<gR3[<<T6Z82%""%1$03/4A&#"*&#"'"#8&*KV4>$BVC<@.4H'4=>/#9CTj9J+"L7B#"",818<%?6RJ:G=KBXO$""#9B>8l4>0?""(,#+0%+,6M1")"$("$63-"$-(.@$=D#"H3N,wM?2.-"D@S<n{@<I3K#""(=@6C"5&1A;:Hy{{{NZI{A-"I*JM3g0:MwTK{YCm;M8%P3{^{c7{<{UP3*8{^A{[l6K/{9>R4EN3MO95<3HN@{-{HB."?O={R{6-H{U8{f7>_GvhhES(XAJF$;%,.<0;t09{EKWTz+>22F;{K{PV8=ZN$)*%J5`-67"@Lb)N-B>H=IB@0$T>@ABg?+7/F0{VH8YG*gHAL=B(&>::\1r_H12%B>J[AI8?/]v/2jf>:XjG<I%GCK>KG("5%"')D1-$*'&85Q;lV8)K-;A0&16,2""",5+(7"==&(,)7"(&8,-46&#6%04LE@"</`9=UJ5I9:T#=/3=5HDZG2+%?3=u{@+HE1((CHB@HI2{V3[-u<M*_4Dp{{Fp`:KAR`{A>H7TR2`{C-t:{RS3Q/i7O@,I:;{z{2Ey:G:V2C]1H?{tAF?"B7{W';>bK378fP:1M@1Il4M{C=WJ:5{^_Q`8Mp&l8G{H;,$eDClcMO{x>G,9$55U3^kU2X%{V^A6Ce8R{:]sWBkG{G@7(Q2\{{uAuH-1+@8&+;2P@2xW]C{{3W7cYH7M0CFq5iA1,{BQ3)[G6*9g{6@701>C6ZwIb58I&;S8L5WAU{ce@L?_n{U8?%F3{z{R8g8W5?0*/%)?:2OGD){-R3c>d=(2%%LIE`=[KK6>21BD2H9"ID-"C3'@=94QTJ{{I-/\^290R+"-)"""','""6#1BnO%GA{n??2(#)+%/.0Ec:y{*IJDI@6:59ha1D2VtG$o{F7U{r{8-BwC*_<6{LAx{f:;60$OK.A<K<;&$F0f@AT^{@3aDDH6`LL?7gA%E3INV;jyL-O52G5W?FSeWbQ:R54)1]>8+"<B?`iOIAP41@58$&;?kX`XI{{4B>pC4=535I<;4L42#7A<."-+7)8+VA)'#&5D=Y\6dO2qtp=A*R2O976L3G+^MB{8{n/;1^C%{{<*s:u2Y_B-H5E2ocKE{Fy>F/wB?R1OS<:23+#&.","6/:M5gK436+u*JW;3=p3N$u#CI/FI2P5ShL:ci"MU%3@$@1"/1e?0Z6O?6Jq_K5{iQP=zmF/Hhv&{W4?cPHfaKPB{IC8%9>>5Og`6I{IH=+E65{{H{>aA*->JF?8A+*,,0lQ?Lb3J).bDUgY@.y5{a77FP<p:{cku[$5+PC13*Cmb3A^T=Wu9M?(><wD{O<p6X{4[@:e@svU8G{w+5D@",v{w<xT@QJ1-{XDFsSS3o{H,LTG.W{I$IF;+9RDX8{{48F=%?N;=[Z70?9=?"""**613".cgom50cAb;.=>K37:`u{lgI,025.PF55G'{qDQB#6KBC2B6'KJ4J.-/%"-33J3>o2Vg7K{Q{H2W%'$'/"'"#@h52?uRB+tEA3OA5xaCD"*%":591$,>D;(<IRAJ?r8x3AuFE]>{L88$i{R4YC(63%*#DFRJ`BmqR{S8KHSNtOQ]`D@[Q7M0;((@K<7&a@8WR&K?U?RFn^KHDV2{q;V{\;,\CSRF@@7?G3O6$?x{KD:%D%O@+@i{>,S;RM3=B{jE1%0]J{O/.d'={{g2PIA*7D=YH{<F[{D7{M{>6R9GT6u2{{;F6`t0kG<G>']@AF.kFC#\ZMAK{DCD(>jH<y{[%tH^OJ{TFHf2xn95{WYk3G{nZ{8gCPIJM<{Z?,{aB8d{=+K=mZ;Y`<I?<t{Oz?'{,9>lfL2C2--25kGIg{K;6"8V""#"D-4#"<QP-{A:vE{{Q-GZ-;=3A5:<9nD7UA7%*KgY=1BGO6b{g_U@N@6:"VA{j4pHJ*1-:JMXHW:pGN40Yze->5<3"1$6/1("),RIP<dIDMIpsMMCzMU>F1iU`{{Wp<EO7:<L{H'I'FgN-"""""$"%'%,&3/",11(&2<QC;]1(/JERxP5PD3O{K%*HFFyR?02G2UBOAdI"","97?LH<1.@>0"")^A{>>gG<G8dp4/3""*/D4:g{IixVNJj=D{Na@a{{{T9mJF)**%;/55jR'D6;A5{3T@83D8=/8>*FP-P4F[YCjLI7>-C$%()6$-P6H@Y{Bh3,QT2W{Fe{CcUX:SL[L<aWY91JDm1P9?f@;{{qN:\=8_=?.?$3DQ1.$&2:1Y6AF7Q^AE={xM>9=/.#<62"'3$5:OIP]89=66AJ2{I{J^{8{ZF5B*L4<2qV[>]$D2+KV==8.p:;o(Z{{A<((++5#<(#%+:6(DN1;io=G<sP?AE9NXK=4d^17X\:3#A8/\rR0=E77*":"&""19$%+*X{:Z4?8ZT1_C5HY\OAc5(C\Z@$a0^D2=UD1Z^EQ:4k5D,Jda${P2I$I5:J('9<"*""%)"A."&*5.K.$""%&$2..LYRRL,9&G&>/$)$&0"""$,/4%H:0'3)'")(+"1GF.jVSE1:"'03:>kv{{j0l<AINIL=p8=dVLjF53/.&.";6+-"4G50M6?BO/8lOL82+P**>AV?UK-(;4+@%,6,$:E:77''01<OS'{W:B98BTp3Ste.D{zG<IA'>:/84J*$:U>VHz00$_WAC7\C'"pZ416,2,0/-,0""#"(+'/"@5I8e=``_3{fIQ^{U=3((-"73+('"&,)-"""#&08-"0"2BJ$?B{weO{Bh@C@kwB7-#E7L{{MO{?{TL8B?]@;scMWB\*<CVNBPJE3JE1?B<HX{NB2"KA{`{]$Y={HH7ZF2U;{tHDaBM26Ng]EDwc"g\56D6&4.+.INT>+%#7FFH?p>F'%"3-;5*,71>,+);CMML&VA?><fX[1fLpvpJ(099Q34X{zHA7TR;B""B3dH1LY^;4CVY@LREPL2;;H:4&#""'"<DGL8{5;JS2JTA2=3,M83@"9;UC3E30>0;75-QA1xKt+u{{2>M{N/?5:YX7/7$O@/q0NP'H36mfFJ3>{m6/{Lw{YRV&{8;BBCm=>`ojTQADS\;=."@T1ZxG)L*#"%"/-0&B@&.3o/]XFy{B9NUgVn>DEin6Q,kZB1V:%FW7KNG4a7NOi=H44Y(q.O35EHFL8U{fI{>DHSbY:U".7(09*a;g$4$$E0A=O^/&8.X*>SI?EM?-VW9:T:A)""&"@[?5)566?qUG4P.{MFvph4Gno)FG$`J5A5GmA<dS;`U{F&O{G3AW>."9;1+8)<&"""")8"+"""#$L/@Arn8c{P@,{b?0`zLF{G5e@6I@orOQH{K=F@;BAVbF1,2.$''#"##"D?$1,K&J9."9I'K>{^7{]>Nzi--"#""""$;4@/;&B)?BHlG{DiN'8;JY3XFJ><{SF;F9{M>b{Ju78FbpV+a2"4$"(3+)*@+83#<**0@(J"S""'6Z5wPIyYH9::1MY1{4gAkdE)&9]D>RxV@)#)&&*?N7VB{XL3JK=?S2mT3200c>>4?CW{{{N?\,{{FkF{BQ+w{7K{{@'Q9:C$K<41>;B<{{na^'y2E>2:+."'"*?45ICVP{F=D/D@S,vu4{A<J15<R3:G{{h5F${/,54K3Jg89{8<y{@;6u:8%2?4_.{tS$rEp8D9r;2fC5{{N:{{{;G6=H@I5<;4m{@NDOUED;"6<3m{HK7?{Z?<3:1UF4R<2Z{l{E.':6?l6F25){i;k5{JHx2Q22_/2;s;{9>6;45;8$,0">(a0JE_1G]0"".:21=C{?O;,I95,%0&0"/-'+.)"$1)6""'/,.$,"(MMI5'J;C2=91M1:^F-\>R7\716#3'+"8T_KJ-xD-@:{Z)={LBL{J\O5/{{4.c:A@n_L9+4t{CUGcF\C{BC;(NJ2FI{;;ND?CTk4LIdi^bA)zkAK/JTp^GLwtTD{^;p{EFM{J=a>_G5{j5{{vtL6g4EJ@*H>7Vx==Z"MjQRL7L"L{{<$,`h290x=&DIISJX;(;@<ekVVWcEnG2pCDE=YsS+Q">CIj{1W]0<<K)wCC=4B;(&6bF2&GQC{t=I>j@g=42,#$C?APT{B?L&;8{c{j'{:nCJ4MW+1:2J[QD{{<@MiF\le"FI7?6_f\9,9NQ73A>2{OT;=8){{tJH;iJ*%$/)+A4-"")$",%6>,%2@PHN:\BSt6R:2C_HA*{b2wN9l%r.-IhE(f9(.R=bS>R'><Jz;@@pc++1V^2JIf8k@h?{gVLO1a98P9%a:8-BOBAfuK>RCDE"?\4cL:IbQ4{{t]'5#EE9LVU(q53&7,_69W=1/'+9-M?A=8EfQQ4_qJ'GO5)@M,"""'"$&2#",#"*)1140Aq;;3"0ct{EP1"E<QQjB9DE<\65CF)BN3QO4:#H&<A:E@C<6uVA=:?3Ig?/1F88;($01N>=:F26<mUb2>{{-G;5{>A^86ORaU2/{@:cOcx8{5HJ74&')%&06"T<$'VJCD4<;#"%"$"3+$35=+&].BE{Un92x2f93.4<1C8{sl6X+G3$=ho'jQTD_1?Epj?N{BN4{c61{7.zJR9\SX?1OA2"/KI?&y94IMYL2#)0,1)++7L9;%"DM.%7>U9EB{{R+{QH=hH{u]SLGoi[J>R<2+78<-146$)0dCAC+U94A,BR:D^B>M:==2"%"(1(GUF{Gcxc{wA6?CNK?e;9AK<QIHc2"C2#$C)6G7[2eD?{oo27A7(@29:4;)<K^6BKFEBk?60$@W>;727*\F;C?VB>68]ju<D{H"E"DdC2S-=9o{BI.,%&<3KI8;B{@-]@&G?C%O3o{lWE{{<6OKG;AB>>>/3X,:G<{N]J{hDi_>9B??:>6S6;2*'#"$#=/{-K03jA>@59&#1J6T<@]9X)#?@DK@Bm8{=ZOV,H@A{tMs=t1EV6JnH?J_2.C<I&(fCT_hD6IFb8L{_N@*HT8E1RJRD>{vaDC{{/2>AXH10CA2+=-$=".$()UF@o4,N2X4:4"&)3him1I'{2[?mX[{{{V8G7F;2Pt@<9@75bEe@.{<FT11NU57:G]D2IxN"C7F?6p8IvE5jD#E{gEKvwk1Uoc<lC%1@;;/5&8&%%"'$".?3g7N)].U-D*$<7I155>:)5;8IGpr69{5{IQ7Oa7FC{\K5MeJ#@2j/O5_AA{;1vVB`W{>?Q>Q\ZYh_>8NRBB{n::LA{cPuAw[]s3<@F4ITA?>.*#&BNYhC@5{m<2Por5Rg)"1A?.UG8avt4?{{?P?P]<{`+uz@F2]g9B><:)]L4jJHF;R6<C{Q3?A;{xX\g{{ExSM{S48*D&&57-0()2:&""*$(-"$"%"1#",1,03-"&2"#'"':""&#$+(6@,23I;4CH(7*;=B</[12&+$C47$IF+'&"$".""#%/*%#,"#"""1Fh{O7FH;;0';3)/6UgBKG?[ZHE39J644'I@)/{s?J2?lmE.%".>?tPyI/K:EB=b3TXG{{{2B{{>5G0s'qH"+&(5Ph-SfQ(;31<"-""*$*&%"&,Av>qHJCI%""%%0?60*T{n3rHFcP{5.c+4541742Son33?63wr7{j{4F{36{Xf@'KEAk{e?acNx6{C>^$GF.7-<I:W"$"@02FIChR;Amv{{?EEB{{8P4[`[g8({A)u2AEZK?LEO;GQ4JP6RM3-A-""#"7D='D4IWo91;)6(+4?DB)M7hMT{:4OX=?D2\F5zo,GqZJ:=</+"0@pi:FI95{9>QEDA{{{68{M{GF?SC?A9{qXAH`n(FOV{F71D5#'$[FI<>];=?#=9{UVwF,UfT>:t@9_T7?/*T)MA2K2$"/`{8Ci:Cd96//5F8cF2XD_82H.2;eI={\UzDN]6{^FEND8ECgiC\t6@A@)?.IH;emEOO<9UQ?Fd3{k3O{U`.b#sE6E{co5v{4J"kc94ZF76n^:(sDL.pI59N5+#,+2@0RMGO,y+4<P5RUd?67@{yA0o{@F5"BV3R{O5SU2H?3C356=dTE+0#""(122)$"),-;/=/7%"$'"236.Y3B55%)%"257Q1no38{{$WJ$N]:S'RM'"&*=Q=SZB<7#`=?w;D93"73YAU77mZYFDF6Lsgp.D(HCJJAAv]^@u;_;a;s+"RW2b[L0s-q{xjLG70H.+q5H*m/;<_8+No3.218hBM_{9FSlL;9mqINxD1"*%&3%2:?1E)-8:++5?%AXAE9uA;H@-""""6%L6q9Z03B#)"")0+1&)F8-{c3{@;ISUJ-8=)I/M&5(A"=aCLZk@9*"5+L8N9=3>$(+0/+B('%"-"=8-+7,-:&\K5U26QL@PL:y{Ch8%J={suKQ{M,B/fW>:=:wgK]5,X,SL__H6X95,"6>\H[V{^8/"PH4rK3@GC>7D1]P1WF:SK78XEc99F1L^c7;/@N{@=.fb2"""U3I9-{wPBHiN?9*"(""0$&&,&,.d^N4=>E{VP{J49&(793LA7=W@-&uS2f;5d9>GN{@q1bW{x7=;#"*Q4:E'"(QNNQI{E8XmQ29{?PM6?5]m=NR5N={`T0D2{4DHE8{leE{d6F9.<.""2-%?@3;[ZRe${C;F:$CP3{Xq1Gtw"=H0r#s4CZM8a/2AX{s<EOA//..31)1""""6V1N_3E"AS;V9HSF6M{{=L?O[{<G4$HPDa{{{03{EA51X&YGB6@'')$"3&"*"/C:<&%)","42#-9jG5;96.AQF]?3L{{YbpXQ:7f285\"bbaPiK>;&-s{X/6[>'.\uS0xe*<G]a3DU6{tOkU+r/HOB1P7*-%",i_A2E9+7?>O9{Nw:.g3cJ79-3BS<ams{K\X2>A2F0+*0CHIU4;AV{nIq/S6`A,+#(2"&2RL;4'C\HWBC{9lF34k++""+,14H,>"lpG7:"EM:JS?/]ED@I:M<v{lGC{X{49e=00@Nekk{Ya?{8){[>M;^^:,gI/>8{HQ;F`4GUCIkG1&-dTC6AAh@2kRG7Y`-7""G?3L?C5{^KM+S7#H/<{pi<>_DG:<J1FHR?9e_U<(8cZJX5n9N-rTAAoaPT`RL<GC<0S=o1d;:@jy1X@AO?9<%ON2CF:1)#"+*AF18-65-_3JG4/.2CM0&?r5h?VNHEPhfOGL{B;RFTV{{{{H7Hpqn0U2l17'""""6""(7"8T0O@G$J:(""7;9ma{RDDX{>C"pYA={{W-cg68k{nVP?irv24P9g4>6>"{[Zrq7A7G{w<6pPA/$"$%I:7IX;t<1lS<C{{@8:JQN:5R{XTqvGRW{AL6%U,Z@SJ4rt5N1XeFn<7{lX{3P85/?>e"ka:=u_/aCGk9{<L({w,Bs<1rwE5")80*9;/)(;"%("""/3:A[<B@%#%6?:0IMHKK{LI2M<L><{CGM4ZHEqJf[/6W^\=IzmSAG^o$V5^{1@KTFLSuB:-*.))51e;F\D>{^I@ZA4uN*'$%3B<"{F{cD>o39{'k"9&"F3zQYD?\Ef9;0=4eM4{]N0EdLX@94Er1D<HI03lX;GZ{C9E(/(_7yFzO?KN3DfU2>zw\WJeE6E;i@]<ASMQ;Q@5K?-*/4":L5PV?9o4BJL{ZY2WRBM^2@RXI='L9\;X4Q6/<+:830O,+0G?iZ&{=7E713(/(B0u{{jV<{{/>N1=M79BH3ANjV8^{{;\{T:8IH@3#`C:?#q(DGM{;]<@{{?[B]XFADAeup1qCB[9{AO9*HR6Mm{9.IW,@#&>;RQ{2<^V#o&6Ga9fsN8H('"""""&")(,@2>2d5cQ:8?(A3Cyqi8F8j,[G_Ns_7M{J6f#T{{3DotyX@L>Wtw*Z3G{GHBs0aj^:M#{H@CBH4Q+QV5UvSHEf{?74+0Y2;?4?:DY<_"0'/0_AS8zO2={z9bSIV=]H84Xl??M76{?6vpBL8U{_A{G{YA:4.7)"LqW2awTn2C{{{{:CK\Zp9PC@u{R3CmB5k-x,4WWDBJE^C2cI1B]I=:E(,*2I@'#**)ITXT3%u?C0&w<H{h7G{<0RBl@NgMAB?q\Q40?0..@A&BeM1>o6w{SAVAp8*HoJ;fkGr*"M9F{RCB?GC{m[_C/kHHO7=Q@GBS{8D${1QN{?;J+D?>@03LwFOK@,C{/{r9{u9VCTN{eB_&`g>?{?6ol9C]iBH_vX?<nB/{yT>IA2f2KKo"IuW/<=/AB5#O7A{j9oQCPFvELR"=IN5[uA)i9mX.{a;@{@e3Hf3{f7J{r{<:cWX9OHR{{{M{VDa{K97$LC<NXM/{8{\O78(7/$."")%"7-23-5.Tmi{o:aSCQ0{AZ==[6I13Z_&g36'@:&"B0A3GL={{{{-7q<G<PR1"""#,&<7)=-c/:B.uJ5ppA1sVG@1)vRX6C<ipPcN%{M7DW{?7=6Y{u5d94)Qm(F25"bv{{HKTU?8c7E:FX9-={<{{78@NLWooBY{FCn]3{{C6A{H?Ib=*<>C+8$22D9e{XU?{{256DGL)=5D`[?g;0[-E?{{{ID6roK({G8(A#I2*07,;,6#"-"BEPCqYHK=<;?:W?`5tL4*$82XbnL(Q8H344293Fv\M8G-{,U<OxIMhhW_@&L72{{n<F+psn;AN'IUuIF{#p/{kE{aBs;{{.DU0UJb6"$%=V{z7go{{<U{f82{=*{2K<0h'LB2G=`{`^B{Mq2D5Q7[SL@sL6Q6U3{{8T6&J>N{{7'N:JA?^9;_8{`fQBpb<293##7*""""%,"0'")""'#E2rU.C#4-""$17>``Q4K$TMY>6"""'2#"E69:5n9(QR9777R,/O4+#<'+.1]9{lMX\'p-T[>:m0>74+*1Q=W8{<K8D?@{^{R({i2UG{Cj2T6^\@-""$"/FE_O<l2Ju.@K7QG5{<o8"D:2S^7D[S:G;A:.VCW1oXL?3JADO4M5.EBX{D6]C5*{@N."FXH:2''.-0/=5:7dY?`wLgLJU%0%+/".SY>S{?7D3k{{U<7%e:{K{JK>7&A<+&1mmU714,(IK?5."7)%8:,;75H@@56eH?2P[7I;2;71rA@/wL;{MoU%N;q<,lbS{Rxv:?8{Q0.&."LFW;E3Vt\=mWFaF{{?;8?{CHbh-?P@{FJi;{\I3%BM9/mH2B9:ClQIC{o={VEG7{<?W{{5O>RA>[7kJ>G0$5"=3aSS\:N<uJ-"3w{7H{[;Z)II51"%jL3'(AUq_N4=*6E3UB?.,*L"6QD2)&0/9L/YK>AOzC>0"LI>])*)>p-^3eIPO;{poTE)2)(Kb9hog(>yn>VDLH270nW0LA4P;GM?6&"'.#&)"/,#"1E<L%B:*.#""""##.;SO8Te16/&36?-RcG.[;=1(+F4N]8q[JV$\9M=A>[?3$71.5E]C4Yi1-*+,0&-L8/c;77sB>RJ8{jr6M'{0X3-A^i\+/>'%5*"""*QA79>C$$0E{{oT%h>e<3{zV)R9Y)n@'$L2f0IJ?;ZA;?zON=oJq@#$C+.+.?B/\^bT+-("$#&*D$%>\=dhm`1]=s9/Lf{dD[f<;ef%W&uB;]@K7i''9$=7o"37`2rJN{Wr4Lcm5;;5%"O{HY[9;{K=US^-@'gW5ZJls{{DOBkIaB{LB{{Mh2zf93M.{PH>:W{HDY28,`93)*;CP;?^dSJ;7O4Q1L91?1vO[L{aX?#K-TH@C.Y5<8JLa{@1x1L:3__"U{z=-_F@GQ9t{jXD{\6"X5b,I*7/He^<phC;A{K<H,H/W1Q{1:U{IDa2MV>ZKqTC*$#$%C2'*1;%1.q(7%nC@e{a{JAK?h5qE,{;s\H6R;{sQH?{05?&D6,-&T_=0mm?9H[8@7$W7rouFr{_1G'l{PN;@Gb{2={_*AH4FDD;FRDQNU8>_4{G<^sQP-^*-;0%hyjUDXC;-{{G76AMC>AkA5E,956T>^G52{M95E\7:4DRBHuI9'%#%2LF?jL:6"6:34=%PU8&""ARSED5^+<=>LZ${{@6L?T{{{8ZKuLEY3hOHse==<;I54"+26&9#HO(I""24?V8{<*{8t4A<J96GFV_dg@Dr{L;5l*ZIr@g%EhzMWwx0A2[;J%&"6=0"-5".,(*)"3)AED8%%'.A."=),"""#""$).-'*""'-))%"'$*+"%/:A"6"".c2@&(+-,M7#M1GA_dT$,9a@{5O+";*";A+?34*O?IG?1E8'N:K:*/7$#0V4,94&?+:BH+25L^#D5E@(7E<$4R49%2"%$>2.Y-"&34-68'"7;G;f4IE5"6->{{6<;4{%{LLs{45$D;Y*k{51Y6;17%6/Z01GG>LY5T:s{y`7Vm%96.DTfK,F{e7GH[={F50jZ3{u{Y0D-++NQNRL.;x{sWF{{/B5@5CoC+GrhD=oJN9_{L:4".yy{xCIR7`D5I.E3h1{iL>kg,1.7#84"""#*':fU5.K1+"$,('>)NFK:oO2IV@G={G=k{f;91;{{`7Z#F""%"'("$#1?EU%dO,F*#"/,""%D""$%,.'?XFd<+)8-MS:M:L9'7"5.7U::N8OB"'$"-.,.&"$$'(0-/,-9%.;AT<HJTz78C6@iC;o:Q3:_JDC@`G2vFB,"@&--;1B`{91myX0LF57HGP25`\NL3TJ?"":L//"=8{5rjcJ7TE>3:7><A{IF2B*2)"7'0--81C6D_')%"""""56761:TRx{8{IF9$H{wG3>'{6JN02BHLj>{`9oHG1vyC?B{U;{y;Uz6g0'A,K<80:I3uq0B74RXSA,,3<C&.13G7L{;(ot?G=T:@)RD($"$%&"3cW:IrE51$8064\.&11=>D?\`C15.{^]='G6{D6H4$C?E<Q4\1[>1I:3l/G(<924e8)j-"""1"AF{GeSX{LWVCIQZ8a8{mo4EynD<>='B?a<O26'*QU=M{;Y8Ea{{4H{UOCL8vD{OFz{Y8I{S=_XF>OK<'2"+;n2Z{{o<I74;^2L7+DTR=9_=pHHF2mb8HKG?*7eB9HKDO,LE2?QasE6:mn?2B0&)Ic{g1i&PHA9u[8?Q\97Pit\28]Scct>9Kc6{{{D-d3{:iMDBW{RL`43g9Z{X?@shP:<;bE.12Ao7i{o9X;C=8B{U;3nA7{sI4>G&"20836vjPN@u{A?GAA6;,&&"'0((#2;1((QLO6{@{@>>>N7_>7O(:-M%5,:ctRCM6Hi{F?GW3B$"9'87("<?cU6MNQFN{H@{yFs{84KH{puNC{=uMDGDB<t={=j(U:=A{4-@XUC{GW>?9HEPLBf;ZXU8BC(C{e61@%Q>Bi<Dd<;A>HKK8GC(N=7\[@E_(w"R?XA`PJ1{{{o)hE9=hEp{g8G{4ZN>QI{+PnUWI5[wP9P43H$KNkhO{XJ6R)n]@A+;65S,Bs5'7&"""$"'.(:M7ZJH>J"&""""4,<GJ2_^?_$bbIQ2DAA&$$<3t2NJ9E`7{8@)$:("F:;WDN>hDY{{I5`1{0Q@BCHD9=:21=UIYH{@Z8+;I?\s{37E{LKBYS7q=mdc7D-"&&7.{v4E6B4=18Y_3CG.A{;@H;D2.&,->7'a;sJ53?K8KC2Z]:?{Ev8<5<FGC1:1"41<EHT95(LJ%-*''(;QF/"&6;OpR@{cD:'))28;)<14/1IIB9Z:716:N(%AC3IFK&%(/$*/BKE7%4PJTE\c((2;@3:&')14',LSK\:B90D=b:%@&,/:GD**O:q<uoDB7{Q:0XNl85F2Ci7bx^BN8{1+1`R5y>{ME:H<2V{?{BaE5)CSM{{_>MD<D:FBXzQ"YMB4[h@8=57VBF$#99F<53&&LRP{^Bvy{F*c";B0cJ3{{snfSNkV?j{Mf5?:?<B%%"<@6XVF>Wx_1{p1LF{2WO'kb6S6[g:1g;E`UrQ4,"9)"$/3PJ8AP"a<84K51CL9,9"$"(+"""'"""""#""$#""J""(6784")."#(""%'%""""&";C1#"++,0)#&""#&+",$"$//""$#""/-"""*%$""$4L.DP7+2\f9L8'?=tTW7.g7-372$9FU8""247n_H=>D6<1&0ESN5p@K1.;3*8"0HCF=-HF:J/:K2;R=Psn>wKN5=8:R8DP?KXZ61?"=;u_qFQQ9p=_S5$A6>{{t7N{{.2F>4:a7>pnIBEQE{Z1W{h61c^:1$0O4(#1)<G5J{QW,%%X4\5E26C?%$'++%)#?;KE%5/=*:f=6>M2<),4-3DR"<K267"#"4""""*""#':LJ8hhE8p)7:Uk;)@/N?U/5V6.%2#4<,""AR"Zcq/"&<fUtA[{2w3.Ey?2@,IU?=+"""+<M6.*E/@O/,cNE2)I5-/"BF<1P9'%"""P(72?h1{Io4+2Z2FCGBT7G\\H&A%K;d;J:*g{{<'U6>^?9*:'`;>rX\Cm.A16L=^9>I9<)+#EbA[{D1XN8t[N4"2;"#&J00D/D6,O[OSpQ3GAJ&4=9*0P:.G.#HQPD0fCEA3P>?BW08J3ccK.*2#$,3;++"(%"""**G2('$+/",[78"+"""""30'>R.6?M92<_=9<6+`61^P5&8/6$&)19F@(FF?&I>,'0")<"5@**G2Q;<0""":59,7-""".+4**8",13(B,.$"	NM:i:1725	ms:i:25890	AS:i:26022	nn:i:0	tp:A:P	cm:i:1262	s1:i:10060	s2:i:6510	de:f:0.0658	RG:Z:GIAB_GM24385_UB_Run3	HP:i:2	PC:i:120	PS:i:16050252
